/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/

#ifndef _chains_vipSingleCameraObjectDetect2Tda3xx_H_
#define _chains_vipSingleCameraObjectDetect2Tda3xx_H_

#include <include/link_api/system.h>
#include <include/link_api/captureLink.h>
#include <include/link_api/algorithmLink_imagePreProcess.h>
#include <include/link_api/algorithmLink_imgPyramid.h>
#include <include/link_api/dupLink.h>
#include <include/link_api/algorithmLink_fpCompute.h>
#include <include/link_api/algorithmLink_objectDetection.h>
#include <include/link_api/algorithmLink_objectClassification.h>
#include <include/link_api/ipcLink.h>
#include <include/link_api/mergeLink.h>
#include <include/link_api/syncLink.h>
#include <include/link_api/algorithmLink_objectDraw.h>
#include <include/link_api/grpxSrcLink.h>
#include <include/link_api/displayLink.h>

typedef struct {
       UInt32    CaptureLinkID;
       UInt32    IPCOut_IPU1_0_EVE1_0LinkID;
       UInt32    IPCIn_EVE1_IPU1_0_0LinkID;
       UInt32    Alg_ImagePreProcessLinkID;
       UInt32    IPCOut_EVE1_IPU1_0_0LinkID;
       UInt32    IPCIn_IPU1_0_EVE1_0LinkID;
       UInt32    Dup_captureLinkID;
       UInt32    Alg_ImgPyramidLinkID;
       UInt32    Dup_imgPyramidLinkID;
       UInt32    IPCOut_IPU1_0_DSP1_2LinkID;
       UInt32    IPCIn_DSP1_IPU1_0_1LinkID;
       UInt32    IPCOut_IPU1_0_EVE1_1LinkID;
       UInt32    IPCIn_EVE1_IPU1_0_1LinkID;
       UInt32    Alg_FPComputeLinkID;
       UInt32    IPCOut_EVE1_DSP1_1LinkID;
       UInt32    IPCIn_DSP1_EVE1_0LinkID;
       UInt32    Alg_ObjectDetectionLinkID;
       UInt32    Merge_objectDetectLinkID;
       UInt32    Sync_objectDetectLinkID;
       UInt32    Alg_ObjectClassificationLinkID;
       UInt32    IPCOut_DSP1_IPU1_0_0LinkID;
       UInt32    IPCIn_IPU1_0_DSP1_1LinkID;
       UInt32    Merge_algLinkID;
       UInt32    Sync_algLinkID;
       UInt32    Alg_ObjectDrawLinkID;
       UInt32    Display_algLinkID;
       UInt32    GrpxSrcLinkID;
       UInt32    Display_GrpxLinkID;

       CaptureLink_CreateParams                CapturePrm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_EVE1_0Prm;
       IpcLink_CreateParams                    IPCIn_EVE1_IPU1_0_0Prm;
       AlgorithmLink_ImagePreProcessCreateParams Alg_ImagePreProcessPrm;
       IpcLink_CreateParams                    IPCOut_EVE1_IPU1_0_0Prm;
       IpcLink_CreateParams                    IPCIn_IPU1_0_EVE1_0Prm;
       DupLink_CreateParams                    Dup_capturePrm;
       AlgorithmLink_ImgPyramidCreateParams    Alg_ImgPyramidPrm;
       DupLink_CreateParams                    Dup_imgPyramidPrm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_DSP1_2Prm;
       IpcLink_CreateParams                    IPCIn_DSP1_IPU1_0_1Prm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_EVE1_1Prm;
       IpcLink_CreateParams                    IPCIn_EVE1_IPU1_0_1Prm;
       AlgorithmLink_FPComputeCreateParams     Alg_FPComputePrm;
       IpcLink_CreateParams                    IPCOut_EVE1_DSP1_1Prm;
       IpcLink_CreateParams                    IPCIn_DSP1_EVE1_0Prm;
       AlgorithmLink_ObjectDetectionCreateParams Alg_ObjectDetectionPrm;
       MergeLink_CreateParams                  Merge_objectDetectPrm;
       SyncLink_CreateParams                   Sync_objectDetectPrm;
       AlgorithmLink_ObjectClassificationCreateParams Alg_ObjectClassificationPrm;
       IpcLink_CreateParams                    IPCOut_DSP1_IPU1_0_0Prm;
       IpcLink_CreateParams                    IPCIn_IPU1_0_DSP1_1Prm;
       MergeLink_CreateParams                  Merge_algPrm;
       SyncLink_CreateParams                   Sync_algPrm;
       AlgorithmLink_ObjectDrawCreateParams    Alg_ObjectDrawPrm;
       DisplayLink_CreateParams                Display_algPrm;
       GrpxSrcLink_CreateParams                GrpxSrcPrm;
       DisplayLink_CreateParams                Display_GrpxPrm;
} chains_vipSingleCameraObjectDetect2Tda3xxObj;

Void chains_vipSingleCameraObjectDetect2Tda3xx_SetLinkId(chains_vipSingleCameraObjectDetect2Tda3xxObj *pObj);

Void chains_vipSingleCameraObjectDetect2Tda3xx_ResetLinkPrms(chains_vipSingleCameraObjectDetect2Tda3xxObj *pObj);

Void chains_vipSingleCameraObjectDetect2Tda3xx_SetPrms(chains_vipSingleCameraObjectDetect2Tda3xxObj *pObj);

Void chains_vipSingleCameraObjectDetect2Tda3xx_ConnectLinks(chains_vipSingleCameraObjectDetect2Tda3xxObj *pObj);

Int32 chains_vipSingleCameraObjectDetect2Tda3xx_Create(chains_vipSingleCameraObjectDetect2Tda3xxObj *pObj, Void *appObj);

Int32 chains_vipSingleCameraObjectDetect2Tda3xx_Start(chains_vipSingleCameraObjectDetect2Tda3xxObj *pObj);

Int32 chains_vipSingleCameraObjectDetect2Tda3xx_Stop(chains_vipSingleCameraObjectDetect2Tda3xxObj *pObj);

Int32 chains_vipSingleCameraObjectDetect2Tda3xx_Delete(chains_vipSingleCameraObjectDetect2Tda3xxObj *pObj);

Void chains_vipSingleCameraObjectDetect2Tda3xx_printBufferStatistics(chains_vipSingleCameraObjectDetect2Tda3xxObj *pObj);

Void chains_vipSingleCameraObjectDetect2Tda3xx_printStatistics(chains_vipSingleCameraObjectDetect2Tda3xxObj *pObj);

Void chains_vipSingleCameraObjectDetect2Tda3xx_SetAppPrms(chains_vipSingleCameraObjectDetect2Tda3xxObj *pObj, Void *appObj);

#endif /* _chains_vipSingleCameraObjectDetect2Tda3xx_H_ */
