/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/

#ifndef _chains_vipSingleCameraLaneDetect_H_
#define _chains_vipSingleCameraLaneDetect_H_

#include <include/link_api/system.h>
#include <include/link_api/captureLink.h>
#include <include/link_api/dupLink.h>
#include <include/link_api/algorithmLink_imagePreProcess.h>
#include <include/link_api/algorithmLink_imgPyramid.h>
#include <include/link_api/algorithmLink_laneDetect.h>
#include <include/link_api/mergeLink.h>
#include <include/link_api/syncLink.h>
#include <include/link_api/algorithmLink_objectDraw.h>
#include <include/link_api/ipcLink.h>
#include <include/link_api/grpxSrcLink.h>
#include <include/link_api/displayLink.h>

typedef struct {
       UInt32    CaptureLinkID;
       UInt32    Dup_captureLinkID;
       UInt32    IPCOut_IPU1_0_EVE1_0LinkID;
       UInt32    IPCIn_EVE1_IPU1_0_0LinkID;
       UInt32    Alg_ImagePreProcessLinkID;
       UInt32    IPCOut_EVE1_IPU1_0_0LinkID;
       UInt32    IPCIn_IPU1_0_EVE1_0LinkID;
       UInt32    Alg_ImgPyramidLinkID;
       UInt32    IPCOut_IPU1_0_DSP1_1LinkID;
       UInt32    IPCIn_DSP1_IPU1_0_0LinkID;
       UInt32    Alg_LaneDetectLinkID;
       UInt32    IPCOut_DSP1_IPU1_0_0LinkID;
       UInt32    IPCIn_IPU1_0_DSP1_1LinkID;
       UInt32    Merge_algLinkID;
       UInt32    IPCOut_IPU1_0_DSP1_2LinkID;
       UInt32    IPCIn_DSP1_IPU1_0_1LinkID;
       UInt32    Sync_algLinkID;
       UInt32    Alg_ObjectDrawLinkID;
       UInt32    IPCOut_DSP1_IPU1_0_1LinkID;
       UInt32    IPCIn_IPU1_0_DSP1_2LinkID;
       UInt32    Display_algLinkID;
       UInt32    GrpxSrcLinkID;
       UInt32    Display_GrpxLinkID;

       CaptureLink_CreateParams                CapturePrm;
       DupLink_CreateParams                    Dup_capturePrm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_EVE1_0Prm;
       IpcLink_CreateParams                    IPCIn_EVE1_IPU1_0_0Prm;
       AlgorithmLink_ImagePreProcessCreateParams Alg_ImagePreProcessPrm;
       IpcLink_CreateParams                    IPCOut_EVE1_IPU1_0_0Prm;
       IpcLink_CreateParams                    IPCIn_IPU1_0_EVE1_0Prm;
       AlgorithmLink_ImgPyramidCreateParams    Alg_ImgPyramidPrm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_DSP1_1Prm;
       IpcLink_CreateParams                    IPCIn_DSP1_IPU1_0_0Prm;
       AlgorithmLink_LaneDetectCreateParams    Alg_LaneDetectPrm;
       IpcLink_CreateParams                    IPCOut_DSP1_IPU1_0_0Prm;
       IpcLink_CreateParams                    IPCIn_IPU1_0_DSP1_1Prm;
       MergeLink_CreateParams                  Merge_algPrm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_DSP1_2Prm;
       IpcLink_CreateParams                    IPCIn_DSP1_IPU1_0_1Prm;
       SyncLink_CreateParams                   Sync_algPrm;
       AlgorithmLink_ObjectDrawCreateParams    Alg_ObjectDrawPrm;
       IpcLink_CreateParams                    IPCOut_DSP1_IPU1_0_1Prm;
       IpcLink_CreateParams                    IPCIn_IPU1_0_DSP1_2Prm;
       DisplayLink_CreateParams                Display_algPrm;
       GrpxSrcLink_CreateParams                GrpxSrcPrm;
       DisplayLink_CreateParams                Display_GrpxPrm;
} chains_vipSingleCameraLaneDetectObj;

Void chains_vipSingleCameraLaneDetect_SetLinkId(chains_vipSingleCameraLaneDetectObj *pObj);

Void chains_vipSingleCameraLaneDetect_ResetLinkPrms(chains_vipSingleCameraLaneDetectObj *pObj);

Void chains_vipSingleCameraLaneDetect_SetPrms(chains_vipSingleCameraLaneDetectObj *pObj);

Void chains_vipSingleCameraLaneDetect_ConnectLinks(chains_vipSingleCameraLaneDetectObj *pObj);

Int32 chains_vipSingleCameraLaneDetect_Create(chains_vipSingleCameraLaneDetectObj *pObj, Void *appObj);

Int32 chains_vipSingleCameraLaneDetect_Start(chains_vipSingleCameraLaneDetectObj *pObj);

Int32 chains_vipSingleCameraLaneDetect_Stop(chains_vipSingleCameraLaneDetectObj *pObj);

Int32 chains_vipSingleCameraLaneDetect_Delete(chains_vipSingleCameraLaneDetectObj *pObj);

Void chains_vipSingleCameraLaneDetect_printBufferStatistics(chains_vipSingleCameraLaneDetectObj *pObj);

Void chains_vipSingleCameraLaneDetect_printStatistics(chains_vipSingleCameraLaneDetectObj *pObj);

Void chains_vipSingleCameraLaneDetect_SetAppPrms(chains_vipSingleCameraLaneDetectObj *pObj, Void *appObj);

#endif /* _chains_vipSingleCameraLaneDetect_H_ */
