/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/

#ifndef _chains_nullSrc_Display_H_
#define _chains_nullSrc_Display_H_

#include <include/link_api/system.h>
#include <include/link_api/nullSrcLink.h>
#include <include/link_api/ipcLink.h>
#include <include/link_api/decLink.h>
#include <include/link_api/vpeLink.h>
#include <include/link_api/displayLink.h>

typedef struct {
       UInt32    NullSourceLinkID;
       UInt32    IPCOut_A15_0_IPU1_0_0LinkID;
       UInt32    IPCIn_IPU1_0_A15_0_0LinkID;
       UInt32    DecodeLinkID;
       UInt32    VPELinkID;
       UInt32    DisplayLinkID;

       NullSrcLink_CreateParams                NullSourcePrm;
       IpcLink_CreateParams                    IPCOut_A15_0_IPU1_0_0Prm;
       IpcLink_CreateParams                    IPCIn_IPU1_0_A15_0_0Prm;
       DecLink_CreateParams                    DecodePrm;
       VpeLink_CreateParams                    VPEPrm;
       DisplayLink_CreateParams                DisplayPrm;
} chains_nullSrc_DisplayObj;

Void chains_nullSrc_Display_SetLinkId(chains_nullSrc_DisplayObj *pObj);

Void chains_nullSrc_Display_ResetLinkPrms(chains_nullSrc_DisplayObj *pObj);

Void chains_nullSrc_Display_SetPrms(chains_nullSrc_DisplayObj *pObj);

Void chains_nullSrc_Display_ConnectLinks(chains_nullSrc_DisplayObj *pObj);

Int32 chains_nullSrc_Display_Create(chains_nullSrc_DisplayObj *pObj, Void *appObj);

Int32 chains_nullSrc_Display_Start(chains_nullSrc_DisplayObj *pObj);

Int32 chains_nullSrc_Display_Stop(chains_nullSrc_DisplayObj *pObj);

Int32 chains_nullSrc_Display_Delete(chains_nullSrc_DisplayObj *pObj);

Void chains_nullSrc_Display_printBufferStatistics(chains_nullSrc_DisplayObj *pObj);

Void chains_nullSrc_Display_printStatistics(chains_nullSrc_DisplayObj *pObj);

Void chains_nullSrc_Display_SetAppPrms(chains_nullSrc_DisplayObj *pObj, Void *appObj);

#endif /* _chains_nullSrc_Display_H_ */
