/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/
#include "chains_nullSrc_Display_priv.h"
Void chains_nullSrc_Display_SetLinkId(chains_nullSrc_DisplayObj *pObj){
       pObj->NullSourceLinkID               = A15_0_LINK (SYSTEM_LINK_ID_NULL_SRC_0);
       pObj->IPCOut_A15_0_IPU1_0_0LinkID    = A15_0_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_IPU1_0_A15_0_0LinkID     = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->DecodeLinkID                   = SYSTEM_LINK_ID_VDEC_0;
       pObj->VPELinkID                      = SYSTEM_LINK_ID_VPE_0;
       pObj->DisplayLinkID                  = SYSTEM_LINK_ID_DISPLAY_0;
}

Void chains_nullSrc_Display_ResetLinkPrms(chains_nullSrc_DisplayObj *pObj){
       NullSrcLink_CreateParams_Init(&pObj->NullSourcePrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_A15_0_IPU1_0_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_IPU1_0_A15_0_0Prm);
       DecLink_CreateParams_Init(&pObj->DecodePrm);
       VpeLink_CreateParams_Init(&pObj->VPEPrm);
       DisplayLink_CreateParams_Init(&pObj->DisplayPrm);
}

Void chains_nullSrc_Display_SetPrms(chains_nullSrc_DisplayObj *pObj){
}

Void chains_nullSrc_Display_ConnectLinks(chains_nullSrc_DisplayObj *pObj){

       //NullSource -> IPCOut_A15_0_IPU1_0_0
       pObj->NullSourcePrm.outQueParams.nextLink = pObj->IPCOut_A15_0_IPU1_0_0LinkID;
       pObj->IPCOut_A15_0_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->NullSourceLinkID;
       pObj->IPCOut_A15_0_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_A15_0_IPU1_0_0 -> IPCIn_IPU1_0_A15_0_0
       pObj->IPCOut_A15_0_IPU1_0_0Prm.outQueParams.nextLink = pObj->IPCIn_IPU1_0_A15_0_0LinkID;
       pObj->IPCIn_IPU1_0_A15_0_0Prm.inQueParams.prevLinkId = pObj->IPCOut_A15_0_IPU1_0_0LinkID;
       pObj->IPCIn_IPU1_0_A15_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_IPU1_0_A15_0_0 -> Decode
       pObj->IPCIn_IPU1_0_A15_0_0Prm.outQueParams.nextLink = pObj->DecodeLinkID;
       pObj->DecodePrm.inQueParams.prevLinkId = pObj->IPCIn_IPU1_0_A15_0_0LinkID;
       pObj->DecodePrm.inQueParams.prevLinkQueId = 0;

       //Decode -> VPE
       pObj->DecodePrm.outQueParams.nextLink = pObj->VPELinkID;
       pObj->VPEPrm.inQueParams.prevLinkId = pObj->DecodeLinkID;
       pObj->VPEPrm.inQueParams.prevLinkQueId = 0;

       //VPE -> Display
       pObj->VPEPrm.outQueParams[0].nextLink = pObj->DisplayLinkID;
       pObj->DisplayPrm.inQueParams.prevLinkId = pObj->VPELinkID;
       pObj->DisplayPrm.inQueParams.prevLinkQueId = 0;

}

Int32 chains_nullSrc_Display_Create(chains_nullSrc_DisplayObj *pObj, Void *appObj){

       Int32 status;

       chains_nullSrc_Display_SetLinkId(pObj);
       chains_nullSrc_Display_ResetLinkPrms(pObj);

       chains_nullSrc_Display_SetPrms(pObj);
       chains_nullSrc_Display_SetAppPrms(pObj, appObj);

       chains_nullSrc_Display_ConnectLinks(pObj);
       status = System_linkCreate(pObj->NullSourceLinkID, &pObj->NullSourcePrm, sizeof(pObj->NullSourcePrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_A15_0_IPU1_0_0LinkID, &pObj->IPCOut_A15_0_IPU1_0_0Prm, sizeof(pObj->IPCOut_A15_0_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_IPU1_0_A15_0_0LinkID, &pObj->IPCIn_IPU1_0_A15_0_0Prm, sizeof(pObj->IPCIn_IPU1_0_A15_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->DecodeLinkID, &pObj->DecodePrm, sizeof(pObj->DecodePrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->VPELinkID, &pObj->VPEPrm, sizeof(pObj->VPEPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->DisplayLinkID, &pObj->DisplayPrm, sizeof(pObj->DisplayPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_nullSrc_Display_Start(chains_nullSrc_DisplayObj *pObj){

       Int32 status;

       status = System_linkStart(pObj->DisplayLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->VPELinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->DecodeLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_IPU1_0_A15_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_A15_0_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->NullSourceLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_nullSrc_Display_Stop(chains_nullSrc_DisplayObj *pObj){

       Int32 status;

       status = System_linkStop(pObj->DisplayLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->VPELinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->DecodeLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_IPU1_0_A15_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_A15_0_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->NullSourceLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_nullSrc_Display_Delete(chains_nullSrc_DisplayObj *pObj){

       Int32 status;

       status = System_linkDelete(pObj->DisplayLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->VPELinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->DecodeLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_IPU1_0_A15_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_A15_0_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->NullSourceLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Void chains_nullSrc_Display_printBufferStatistics(chains_nullSrc_DisplayObj *pObj){
       System_linkPrintBufferStatistics(pObj->NullSourceLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_A15_0_IPU1_0_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_IPU1_0_A15_0_0LinkID);
       System_linkPrintBufferStatistics(pObj->DecodeLinkID);
       System_linkPrintBufferStatistics(pObj->VPELinkID);
       System_linkPrintBufferStatistics(pObj->DisplayLinkID);
       Task_sleep(500);
}

Void chains_nullSrc_Display_printStatistics(chains_nullSrc_DisplayObj *pObj){
       System_linkPrintStatistics(pObj->NullSourceLinkID);
       System_linkPrintStatistics(pObj->IPCOut_A15_0_IPU1_0_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_IPU1_0_A15_0_0LinkID);
       System_linkPrintStatistics(pObj->DecodeLinkID);
       System_linkPrintStatistics(pObj->VPELinkID);
       System_linkPrintStatistics(pObj->DisplayLinkID);
       Task_sleep(500);
}

