/*
*******************************************************************************
*
* Copyright (C) 2016 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/

#ifndef _chains_vipSingleCamOpenCVCanny_H_
#define _chains_vipSingleCamOpenCVCanny_H_

#include <include/link_api/system.h>
#include <include/link_api/captureLink.h>
#include <include/link_api/algorithmLink.h>
#include <include/link_api/algorithmLink_opencvCanny.h>
#include <include/link_api/ipcLink.h>
#include <include/link_api/grpxSrcLink.h>
#include <include/link_api/displayLink.h>

typedef struct {
       UInt32    CaptureLinkID;
       UInt32    IPCOut_IPU1_0_A15_0_0LinkID;
       UInt32    IPCIn_A15_0_IPU1_0_0LinkID;
       UInt32    Alg_OpenCVCannyLinkID;
       UInt32    IPCOut_A15_0_IPU1_0_0LinkID;
       UInt32    IPCIn_IPU1_0_A15_0_0LinkID;
       UInt32    Display_VideoLinkID;
       UInt32    GrpxSrcLinkID;
       UInt32    Display_GrpxLinkID;

       CaptureLink_CreateParams                CapturePrm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_A15_0_0Prm;
       IpcLink_CreateParams                    IPCIn_A15_0_IPU1_0_0Prm;
       AlgorithmLink_OpenCVCannyCreateParams   Alg_OpenCVCannyPrm;
       IpcLink_CreateParams                    IPCOut_A15_0_IPU1_0_0Prm;
       IpcLink_CreateParams                    IPCIn_IPU1_0_A15_0_0Prm;
       DisplayLink_CreateParams                Display_VideoPrm;
       GrpxSrcLink_CreateParams                GrpxSrcPrm;
       DisplayLink_CreateParams                Display_GrpxPrm;
} chains_vipSingleCamOpenCVCannyObj;

Void chains_vipSingleCamOpenCVCanny_SetLinkId(chains_vipSingleCamOpenCVCannyObj *pObj);

Void chains_vipSingleCamOpenCVCanny_ResetLinkPrms(chains_vipSingleCamOpenCVCannyObj *pObj);

Void chains_vipSingleCamOpenCVCanny_SetPrms(chains_vipSingleCamOpenCVCannyObj *pObj);

Void chains_vipSingleCamOpenCVCanny_ConnectLinks(chains_vipSingleCamOpenCVCannyObj *pObj);

Int32 chains_vipSingleCamOpenCVCanny_Create(chains_vipSingleCamOpenCVCannyObj *pObj, Void *appObj);

Int32 chains_vipSingleCamOpenCVCanny_Start(chains_vipSingleCamOpenCVCannyObj *pObj);

Int32 chains_vipSingleCamOpenCVCanny_Stop(chains_vipSingleCamOpenCVCannyObj *pObj);

Int32 chains_vipSingleCamOpenCVCanny_Delete(chains_vipSingleCamOpenCVCannyObj *pObj);

Void chains_vipSingleCamOpenCVCanny_printBufferStatistics(chains_vipSingleCamOpenCVCannyObj *pObj);

Void chains_vipSingleCamOpenCVCanny_printStatistics(chains_vipSingleCamOpenCVCannyObj *pObj);

Void chains_vipSingleCamOpenCVCanny_SetAppPrms(chains_vipSingleCamOpenCVCannyObj *pObj, Void *appObj);

#endif /* _chains_vipSingleCamOpenCVCanny_H_ */
