/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/

#ifndef _chains_vipSingleCamFrameCopySgxDisplay_H_
#define _chains_vipSingleCamFrameCopySgxDisplay_H_

#include <include/link_api/system.h>
#include <include/link_api/captureLink.h>
#include <include/link_api/algorithmLink_frameCopy.h>
#include <include/link_api/sgxFrmcpyLink.h>
#include <include/link_api/ipcLink.h>
#include <include/link_api/grpxSrcLink.h>
#include <include/link_api/displayLink.h>

typedef struct {
       UInt32    CaptureLinkID;
       UInt32    IPCOut_IPU1_0_A15_0_0LinkID;
       UInt32    IPCIn_A15_0_IPU1_0_0LinkID;
       UInt32    Alg_FrameCopyLinkID;
       UInt32    SgxFrmcpyLinkID;
       UInt32    IPCOut_A15_0_IPU1_0_0LinkID;
       UInt32    IPCIn_IPU1_0_A15_0_0LinkID;
       UInt32    Display_M4LinkID;
       UInt32    GrpxSrcLinkID;
       UInt32    Display_GrpxLinkID;

       CaptureLink_CreateParams                CapturePrm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_A15_0_0Prm;
       IpcLink_CreateParams                    IPCIn_A15_0_IPU1_0_0Prm;
       AlgorithmLink_FrameCopyCreateParams     Alg_FrameCopyPrm;
       SgxFrmcpyLink_CreateParams              SgxFrmcpyPrm;
       IpcLink_CreateParams                    IPCOut_A15_0_IPU1_0_0Prm;
       IpcLink_CreateParams                    IPCIn_IPU1_0_A15_0_0Prm;
       DisplayLink_CreateParams                Display_M4Prm;
       GrpxSrcLink_CreateParams                GrpxSrcPrm;
       DisplayLink_CreateParams                Display_GrpxPrm;
} chains_vipSingleCamFrameCopySgxDisplayObj;

Void chains_vipSingleCamFrameCopySgxDisplay_SetLinkId(chains_vipSingleCamFrameCopySgxDisplayObj *pObj);

Void chains_vipSingleCamFrameCopySgxDisplay_ResetLinkPrms(chains_vipSingleCamFrameCopySgxDisplayObj *pObj);

Void chains_vipSingleCamFrameCopySgxDisplay_SetPrms(chains_vipSingleCamFrameCopySgxDisplayObj *pObj);

Void chains_vipSingleCamFrameCopySgxDisplay_ConnectLinks(chains_vipSingleCamFrameCopySgxDisplayObj *pObj);

Int32 chains_vipSingleCamFrameCopySgxDisplay_Create(chains_vipSingleCamFrameCopySgxDisplayObj *pObj, Void *appObj);

Int32 chains_vipSingleCamFrameCopySgxDisplay_Start(chains_vipSingleCamFrameCopySgxDisplayObj *pObj);

Int32 chains_vipSingleCamFrameCopySgxDisplay_Stop(chains_vipSingleCamFrameCopySgxDisplayObj *pObj);

Int32 chains_vipSingleCamFrameCopySgxDisplay_Delete(chains_vipSingleCamFrameCopySgxDisplayObj *pObj);

Void chains_vipSingleCamFrameCopySgxDisplay_printBufferStatistics(chains_vipSingleCamFrameCopySgxDisplayObj *pObj);

Void chains_vipSingleCamFrameCopySgxDisplay_printStatistics(chains_vipSingleCamFrameCopySgxDisplayObj *pObj);

Void chains_vipSingleCamFrameCopySgxDisplay_SetAppPrms(chains_vipSingleCamFrameCopySgxDisplayObj *pObj, Void *appObj);

#endif /* _chains_vipSingleCamFrameCopySgxDisplay_H_ */
