/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/
#include "chains_lvdsVipMultiCam_Sgx3Dsrv_priv.h"
Void chains_lvdsVipMultiCam_Sgx3Dsrv_SetLinkId(chains_lvdsVipMultiCam_Sgx3DsrvObj *pObj){
       pObj->CaptureLinkID                  = SYSTEM_LINK_ID_CAPTURE_0;
       pObj->Dup_sv_orgLinkID               = IPU1_0_LINK (SYSTEM_LINK_ID_DUP_0);
       pObj->SyncLinkID                     = IPU1_0_LINK (SYSTEM_LINK_ID_SYNC_2);
       pObj->Dup_svLinkID                   = IPU1_0_LINK (SYSTEM_LINK_ID_DUP_1);
       pObj->IPCOut_IPU1_0_A15_0_2LinkID    = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_OUT_2);
       pObj->IPCIn_A15_0_IPU1_0_0LinkID     = A15_0_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->IPCOut_IPU1_0_DSP1_1LinkID     = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_OUT_1);
       pObj->IPCIn_DSP1_IPU1_0_1LinkID      = DSP1_LINK (SYSTEM_LINK_ID_IPC_IN_1);
       pObj->IPCOut_IPU1_0_DSP1_0LinkID     = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_DSP1_IPU1_0_0LinkID      = DSP1_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->Alg_GeoAlign3DLinkID           = DSP1_LINK (SYSTEM_LINK_ID_ALG_0);
       pObj->IPCOut_DSP1_A15_0_1LinkID      = DSP1_LINK (SYSTEM_LINK_ID_IPC_OUT_1);
       pObj->IPCIn_A15_0_DSP1_2LinkID       = A15_0_LINK (SYSTEM_LINK_ID_IPC_IN_2);
       pObj->Alg_SynthesisLinkID            = DSP1_LINK (SYSTEM_LINK_ID_ALG_1);
       pObj->IPCOut_DSP1_A15_0_2LinkID      = DSP1_LINK (SYSTEM_LINK_ID_IPC_OUT_2);
       pObj->IPCIn_A15_0_DSP1_3LinkID       = A15_0_LINK (SYSTEM_LINK_ID_IPC_IN_3);
       pObj->Alg_PhotoAlignLinkID           = DSP1_LINK (SYSTEM_LINK_ID_ALG_2);
       pObj->IPCOut_DSP1_A15_0_0LinkID      = DSP1_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_A15_0_DSP1_1LinkID       = A15_0_LINK (SYSTEM_LINK_ID_IPC_IN_1);
       pObj->Sgx3DsrvLinkID                 = SYSTEM_LINK_ID_SGX3DSRV_0;
       pObj->IPCOut_A15_0_IPU1_0_0LinkID    = A15_0_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_IPU1_0_A15_0_0LinkID     = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->Display_M4LinkID               = SYSTEM_LINK_ID_DISPLAY_0;
       pObj->SelectLinkID                   = IPU1_0_LINK (SYSTEM_LINK_ID_SELECT_0);
       pObj->VPE_sv_org2LinkID              = SYSTEM_LINK_ID_VPE_0;
       pObj->Sync_sv_org2LinkID             = IPU1_0_LINK (SYSTEM_LINK_ID_SYNC_1);
       pObj->Alg_DmaSwMs_sv_org2LinkID      = IPU1_0_LINK (SYSTEM_LINK_ID_ALG_1);
       pObj->Display_sv_org2LinkID          = SYSTEM_LINK_ID_DISPLAY_1;
       pObj->VPE_sv_org1LinkID              = SYSTEM_LINK_ID_VPE_1;
       pObj->Sync_sv_org1LinkID             = IPU1_0_LINK (SYSTEM_LINK_ID_SYNC_0);
       pObj->Alg_DmaSwMs_sv_org1LinkID      = IPU1_0_LINK (SYSTEM_LINK_ID_ALG_0);
       pObj->Display_sv_org1LinkID          = SYSTEM_LINK_ID_DISPLAY_2;
       pObj->NullLinkID                     = DSP1_LINK (SYSTEM_LINK_ID_NULL_0);
       pObj->GrpxSrcLinkID                  = IPU1_0_LINK (SYSTEM_LINK_ID_GRPX_SRC_0);
       pObj->Display_GrpxLinkID             = SYSTEM_LINK_ID_DISPLAY_3;
}

Void chains_lvdsVipMultiCam_Sgx3Dsrv_ResetLinkPrms(chains_lvdsVipMultiCam_Sgx3DsrvObj *pObj){
       CaptureLink_CreateParams_Init(&pObj->CapturePrm);
       DupLink_CreateParams_Init(&pObj->Dup_sv_orgPrm);
       SyncLink_CreateParams_Init(&pObj->SyncPrm);
       DupLink_CreateParams_Init(&pObj->Dup_svPrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_IPU1_0_A15_0_2Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_A15_0_IPU1_0_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_IPU1_0_DSP1_1Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_DSP1_IPU1_0_1Prm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_IPU1_0_DSP1_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_DSP1_IPU1_0_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_DSP1_A15_0_1Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_A15_0_DSP1_2Prm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_DSP1_A15_0_2Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_A15_0_DSP1_3Prm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_DSP1_A15_0_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_A15_0_DSP1_1Prm);
       Sgx3DsrvLink_CreateParams_Init(&pObj->Sgx3DsrvPrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_A15_0_IPU1_0_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_IPU1_0_A15_0_0Prm);
       DisplayLink_CreateParams_Init(&pObj->Display_M4Prm);
       SelectLink_CreateParams_Init(&pObj->SelectPrm);
       VpeLink_CreateParams_Init(&pObj->VPE_sv_org2Prm);
       SyncLink_CreateParams_Init(&pObj->Sync_sv_org2Prm);
       AlgorithmLink_DmaSwMsCreateParams_Init(&pObj->Alg_DmaSwMs_sv_org2Prm);
       DisplayLink_CreateParams_Init(&pObj->Display_sv_org2Prm);
       VpeLink_CreateParams_Init(&pObj->VPE_sv_org1Prm);
       SyncLink_CreateParams_Init(&pObj->Sync_sv_org1Prm);
       AlgorithmLink_DmaSwMsCreateParams_Init(&pObj->Alg_DmaSwMs_sv_org1Prm);
       DisplayLink_CreateParams_Init(&pObj->Display_sv_org1Prm);
       NullLink_CreateParams_Init (&pObj->NullPrm);
       GrpxSrcLink_CreateParams_Init(&pObj->GrpxSrcPrm);
       DisplayLink_CreateParams_Init(&pObj->Display_GrpxPrm);
}

Void chains_lvdsVipMultiCam_Sgx3Dsrv_SetPrms(chains_lvdsVipMultiCam_Sgx3DsrvObj *pObj){
       (pObj->Dup_sv_orgPrm).numOutQue = 2;
       (pObj->Dup_svPrm).numOutQue = 3;
       (pObj->Alg_GeoAlign3DPrm).baseClassCreate.size  = sizeof(AlgorithmLink_GAlign3DCreateParams);
       (pObj->Alg_GeoAlign3DPrm).baseClassCreate.algId  = ALGORITHM_LINK_DSP_ALG_GALIGNMENT_3D;
       (pObj->Alg_SynthesisPrm).baseClassCreate.size  = sizeof(AlgorithmLink_SynthesisCreateParams);
       (pObj->Alg_SynthesisPrm).baseClassCreate.algId  = ALGORITHM_LINK_DSP_ALG_SYNTHESIS;
       (pObj->Alg_PhotoAlignPrm).baseClassCreate.size  = sizeof(AlgorithmLink_PAlignCreateParams);
       (pObj->Alg_PhotoAlignPrm).baseClassCreate.algId  = ALGORITHM_LINK_DSP_ALG_PALIGNMENT;
       (pObj->SelectPrm).numOutQue = 2;
       (pObj->Alg_DmaSwMs_sv_org2Prm).baseClassCreate.size  = sizeof(AlgorithmLink_DmaSwMsCreateParams);
       (pObj->Alg_DmaSwMs_sv_org2Prm).baseClassCreate.algId  = ALGORITHM_LINK_IPU_ALG_DMA_SWMS;
       (pObj->Alg_DmaSwMs_sv_org1Prm).baseClassCreate.size  = sizeof(AlgorithmLink_DmaSwMsCreateParams);
       (pObj->Alg_DmaSwMs_sv_org1Prm).baseClassCreate.algId  = ALGORITHM_LINK_IPU_ALG_DMA_SWMS;
       (pObj->NullPrm).numInQue = 1;
}

Void chains_lvdsVipMultiCam_Sgx3Dsrv_ConnectLinks(chains_lvdsVipMultiCam_Sgx3DsrvObj *pObj){

       //Capture -> Dup_sv_org
       pObj->CapturePrm.outQueParams.nextLink = pObj->Dup_sv_orgLinkID;
       pObj->Dup_sv_orgPrm.inQueParams.prevLinkId = pObj->CaptureLinkID;
       pObj->Dup_sv_orgPrm.inQueParams.prevLinkQueId = 0;

       //Dup_sv_org -> Select
       pObj->Dup_sv_orgPrm.outQueParams[0].nextLink = pObj->SelectLinkID;
       pObj->SelectPrm.inQueParams.prevLinkId = pObj->Dup_sv_orgLinkID;
       pObj->SelectPrm.inQueParams.prevLinkQueId = 0;

       //Dup_sv_org -> Sync
       pObj->Dup_sv_orgPrm.outQueParams[1].nextLink = pObj->SyncLinkID;
       pObj->SyncPrm.inQueParams.prevLinkId = pObj->Dup_sv_orgLinkID;
       pObj->SyncPrm.inQueParams.prevLinkQueId = 1;

       //Sync -> Dup_sv
       pObj->SyncPrm.outQueParams.nextLink = pObj->Dup_svLinkID;
       pObj->Dup_svPrm.inQueParams.prevLinkId = pObj->SyncLinkID;
       pObj->Dup_svPrm.inQueParams.prevLinkQueId = 0;

       //Dup_sv -> IPCOut_IPU1_0_DSP1_0
       pObj->Dup_svPrm.outQueParams[0].nextLink = pObj->IPCOut_IPU1_0_DSP1_0LinkID;
       pObj->IPCOut_IPU1_0_DSP1_0Prm.inQueParams.prevLinkId = pObj->Dup_svLinkID;
       pObj->IPCOut_IPU1_0_DSP1_0Prm.inQueParams.prevLinkQueId = 0;

       //Dup_sv -> IPCOut_IPU1_0_DSP1_1
       pObj->Dup_svPrm.outQueParams[1].nextLink = pObj->IPCOut_IPU1_0_DSP1_1LinkID;
       pObj->IPCOut_IPU1_0_DSP1_1Prm.inQueParams.prevLinkId = pObj->Dup_svLinkID;
       pObj->IPCOut_IPU1_0_DSP1_1Prm.inQueParams.prevLinkQueId = 1;

       //Dup_sv -> IPCOut_IPU1_0_A15_0_2
       pObj->Dup_svPrm.outQueParams[2].nextLink = pObj->IPCOut_IPU1_0_A15_0_2LinkID;
       pObj->IPCOut_IPU1_0_A15_0_2Prm.inQueParams.prevLinkId = pObj->Dup_svLinkID;
       pObj->IPCOut_IPU1_0_A15_0_2Prm.inQueParams.prevLinkQueId = 2;

       //IPCOut_IPU1_0_A15_0_2 -> IPCIn_A15_0_IPU1_0_0
       pObj->IPCOut_IPU1_0_A15_0_2Prm.outQueParams.nextLink = pObj->IPCIn_A15_0_IPU1_0_0LinkID;
       pObj->IPCIn_A15_0_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->IPCOut_IPU1_0_A15_0_2LinkID;
       pObj->IPCIn_A15_0_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_A15_0_IPU1_0_0 -> Sgx3Dsrv
       pObj->IPCIn_A15_0_IPU1_0_0Prm.outQueParams.nextLink = pObj->Sgx3DsrvLinkID;
       pObj->Sgx3DsrvPrm.inQueParams[0].prevLinkId = pObj->IPCIn_A15_0_IPU1_0_0LinkID;
       pObj->Sgx3DsrvPrm.inQueParams[0].prevLinkQueId = 0;

       //IPCOut_IPU1_0_DSP1_1 -> IPCIn_DSP1_IPU1_0_1
       pObj->IPCOut_IPU1_0_DSP1_1Prm.outQueParams.nextLink = pObj->IPCIn_DSP1_IPU1_0_1LinkID;
       pObj->IPCIn_DSP1_IPU1_0_1Prm.inQueParams.prevLinkId = pObj->IPCOut_IPU1_0_DSP1_1LinkID;
       pObj->IPCIn_DSP1_IPU1_0_1Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_DSP1_IPU1_0_1 -> Alg_Synthesis
       pObj->IPCIn_DSP1_IPU1_0_1Prm.outQueParams.nextLink = pObj->Alg_SynthesisLinkID;
       pObj->Alg_SynthesisPrm.inQueParams[0].prevLinkId = pObj->IPCIn_DSP1_IPU1_0_1LinkID;
       pObj->Alg_SynthesisPrm.inQueParams[0].prevLinkQueId = 0;

       //IPCOut_IPU1_0_DSP1_0 -> IPCIn_DSP1_IPU1_0_0
       pObj->IPCOut_IPU1_0_DSP1_0Prm.outQueParams.nextLink = pObj->IPCIn_DSP1_IPU1_0_0LinkID;
       pObj->IPCIn_DSP1_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->IPCOut_IPU1_0_DSP1_0LinkID;
       pObj->IPCIn_DSP1_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_DSP1_IPU1_0_0 -> Alg_GeoAlign3D
       pObj->IPCIn_DSP1_IPU1_0_0Prm.outQueParams.nextLink = pObj->Alg_GeoAlign3DLinkID;
       pObj->Alg_GeoAlign3DPrm.inQueParams[0].prevLinkId = pObj->IPCIn_DSP1_IPU1_0_0LinkID;
       pObj->Alg_GeoAlign3DPrm.inQueParams[0].prevLinkQueId = 0;

       //Alg_GeoAlign3D -> Alg_Synthesis
       pObj->Alg_GeoAlign3DPrm.outQueParams[0].nextLink = pObj->Alg_SynthesisLinkID;
       pObj->Alg_SynthesisPrm.inQueParams[1].prevLinkId = pObj->Alg_GeoAlign3DLinkID;
       pObj->Alg_SynthesisPrm.inQueParams[1].prevLinkQueId = 0;

       //Alg_GeoAlign3D -> IPCOut_DSP1_A15_0_1
       pObj->Alg_GeoAlign3DPrm.outQueParams[1].nextLink = pObj->IPCOut_DSP1_A15_0_1LinkID;
       pObj->IPCOut_DSP1_A15_0_1Prm.inQueParams.prevLinkId = pObj->Alg_GeoAlign3DLinkID;
       pObj->IPCOut_DSP1_A15_0_1Prm.inQueParams.prevLinkQueId = 1;

       //IPCOut_DSP1_A15_0_1 -> IPCIn_A15_0_DSP1_2
       pObj->IPCOut_DSP1_A15_0_1Prm.outQueParams.nextLink = pObj->IPCIn_A15_0_DSP1_2LinkID;
       pObj->IPCIn_A15_0_DSP1_2Prm.inQueParams.prevLinkId = pObj->IPCOut_DSP1_A15_0_1LinkID;
       pObj->IPCIn_A15_0_DSP1_2Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_A15_0_DSP1_2 -> Sgx3Dsrv
       pObj->IPCIn_A15_0_DSP1_2Prm.outQueParams.nextLink = pObj->Sgx3DsrvLinkID;
       pObj->Sgx3DsrvPrm.inQueParams[2].prevLinkId = pObj->IPCIn_A15_0_DSP1_2LinkID;
       pObj->Sgx3DsrvPrm.inQueParams[2].prevLinkQueId = 0;

       //Alg_Synthesis -> Null
       pObj->Alg_SynthesisPrm.outQueParams[0].nextLink = pObj->NullLinkID;
       pObj->NullPrm.inQueParams[0].prevLinkId = pObj->Alg_SynthesisLinkID;
       pObj->NullPrm.inQueParams[0].prevLinkQueId = 0;

       //Alg_Synthesis -> Alg_PhotoAlign
       pObj->Alg_SynthesisPrm.outQueParams[1].nextLink = pObj->Alg_PhotoAlignLinkID;
       pObj->Alg_PhotoAlignPrm.inQueParams[0].prevLinkId = pObj->Alg_SynthesisLinkID;
       pObj->Alg_PhotoAlignPrm.inQueParams[0].prevLinkQueId = 1;

       //Alg_Synthesis -> IPCOut_DSP1_A15_0_2
       pObj->Alg_SynthesisPrm.outQueParams[2].nextLink = pObj->IPCOut_DSP1_A15_0_2LinkID;
       pObj->IPCOut_DSP1_A15_0_2Prm.inQueParams.prevLinkId = pObj->Alg_SynthesisLinkID;
       pObj->IPCOut_DSP1_A15_0_2Prm.inQueParams.prevLinkQueId = 2;

       //IPCOut_DSP1_A15_0_2 -> IPCIn_A15_0_DSP1_3
       pObj->IPCOut_DSP1_A15_0_2Prm.outQueParams.nextLink = pObj->IPCIn_A15_0_DSP1_3LinkID;
       pObj->IPCIn_A15_0_DSP1_3Prm.inQueParams.prevLinkId = pObj->IPCOut_DSP1_A15_0_2LinkID;
       pObj->IPCIn_A15_0_DSP1_3Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_A15_0_DSP1_3 -> Sgx3Dsrv
       pObj->IPCIn_A15_0_DSP1_3Prm.outQueParams.nextLink = pObj->Sgx3DsrvLinkID;
       pObj->Sgx3DsrvPrm.inQueParams[3].prevLinkId = pObj->IPCIn_A15_0_DSP1_3LinkID;
       pObj->Sgx3DsrvPrm.inQueParams[3].prevLinkQueId = 0;

       //Alg_PhotoAlign -> IPCOut_DSP1_A15_0_0
       pObj->Alg_PhotoAlignPrm.outQueParams[0].nextLink = pObj->IPCOut_DSP1_A15_0_0LinkID;
       pObj->IPCOut_DSP1_A15_0_0Prm.inQueParams.prevLinkId = pObj->Alg_PhotoAlignLinkID;
       pObj->IPCOut_DSP1_A15_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_DSP1_A15_0_0 -> IPCIn_A15_0_DSP1_1
       pObj->IPCOut_DSP1_A15_0_0Prm.outQueParams.nextLink = pObj->IPCIn_A15_0_DSP1_1LinkID;
       pObj->IPCIn_A15_0_DSP1_1Prm.inQueParams.prevLinkId = pObj->IPCOut_DSP1_A15_0_0LinkID;
       pObj->IPCIn_A15_0_DSP1_1Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_A15_0_DSP1_1 -> Sgx3Dsrv
       pObj->IPCIn_A15_0_DSP1_1Prm.outQueParams.nextLink = pObj->Sgx3DsrvLinkID;
       pObj->Sgx3DsrvPrm.inQueParams[1].prevLinkId = pObj->IPCIn_A15_0_DSP1_1LinkID;
       pObj->Sgx3DsrvPrm.inQueParams[1].prevLinkQueId = 0;

       //Sgx3Dsrv -> IPCOut_A15_0_IPU1_0_0
       pObj->Sgx3DsrvPrm.outQueParams.nextLink = pObj->IPCOut_A15_0_IPU1_0_0LinkID;
       pObj->IPCOut_A15_0_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->Sgx3DsrvLinkID;
       pObj->IPCOut_A15_0_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_A15_0_IPU1_0_0 -> IPCIn_IPU1_0_A15_0_0
       pObj->IPCOut_A15_0_IPU1_0_0Prm.outQueParams.nextLink = pObj->IPCIn_IPU1_0_A15_0_0LinkID;
       pObj->IPCIn_IPU1_0_A15_0_0Prm.inQueParams.prevLinkId = pObj->IPCOut_A15_0_IPU1_0_0LinkID;
       pObj->IPCIn_IPU1_0_A15_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_IPU1_0_A15_0_0 -> Display_M4
       pObj->IPCIn_IPU1_0_A15_0_0Prm.outQueParams.nextLink = pObj->Display_M4LinkID;
       pObj->Display_M4Prm.inQueParams.prevLinkId = pObj->IPCIn_IPU1_0_A15_0_0LinkID;
       pObj->Display_M4Prm.inQueParams.prevLinkQueId = 0;

       //Select -> VPE_sv_org1
       pObj->SelectPrm.outQueParams[0].nextLink = pObj->VPE_sv_org1LinkID;
       pObj->VPE_sv_org1Prm.inQueParams.prevLinkId = pObj->SelectLinkID;
       pObj->VPE_sv_org1Prm.inQueParams.prevLinkQueId = 0;

       //Select -> VPE_sv_org2
       pObj->SelectPrm.outQueParams[1].nextLink = pObj->VPE_sv_org2LinkID;
       pObj->VPE_sv_org2Prm.inQueParams.prevLinkId = pObj->SelectLinkID;
       pObj->VPE_sv_org2Prm.inQueParams.prevLinkQueId = 1;

       //VPE_sv_org2 -> Sync_sv_org2
       pObj->VPE_sv_org2Prm.outQueParams[0].nextLink = pObj->Sync_sv_org2LinkID;
       pObj->Sync_sv_org2Prm.inQueParams.prevLinkId = pObj->VPE_sv_org2LinkID;
       pObj->Sync_sv_org2Prm.inQueParams.prevLinkQueId = 0;

       //Sync_sv_org2 -> Alg_DmaSwMs_sv_org2
       pObj->Sync_sv_org2Prm.outQueParams.nextLink = pObj->Alg_DmaSwMs_sv_org2LinkID;
       pObj->Alg_DmaSwMs_sv_org2Prm.inQueParams.prevLinkId = pObj->Sync_sv_org2LinkID;
       pObj->Alg_DmaSwMs_sv_org2Prm.inQueParams.prevLinkQueId = 0;

       //Alg_DmaSwMs_sv_org2 -> Display_sv_org2
       pObj->Alg_DmaSwMs_sv_org2Prm.outQueParams.nextLink = pObj->Display_sv_org2LinkID;
       pObj->Display_sv_org2Prm.inQueParams.prevLinkId = pObj->Alg_DmaSwMs_sv_org2LinkID;
       pObj->Display_sv_org2Prm.inQueParams.prevLinkQueId = 0;

       //VPE_sv_org1 -> Sync_sv_org1
       pObj->VPE_sv_org1Prm.outQueParams[0].nextLink = pObj->Sync_sv_org1LinkID;
       pObj->Sync_sv_org1Prm.inQueParams.prevLinkId = pObj->VPE_sv_org1LinkID;
       pObj->Sync_sv_org1Prm.inQueParams.prevLinkQueId = 0;

       //Sync_sv_org1 -> Alg_DmaSwMs_sv_org1
       pObj->Sync_sv_org1Prm.outQueParams.nextLink = pObj->Alg_DmaSwMs_sv_org1LinkID;
       pObj->Alg_DmaSwMs_sv_org1Prm.inQueParams.prevLinkId = pObj->Sync_sv_org1LinkID;
       pObj->Alg_DmaSwMs_sv_org1Prm.inQueParams.prevLinkQueId = 0;

       //Alg_DmaSwMs_sv_org1 -> Display_sv_org1
       pObj->Alg_DmaSwMs_sv_org1Prm.outQueParams.nextLink = pObj->Display_sv_org1LinkID;
       pObj->Display_sv_org1Prm.inQueParams.prevLinkId = pObj->Alg_DmaSwMs_sv_org1LinkID;
       pObj->Display_sv_org1Prm.inQueParams.prevLinkQueId = 0;

       //GrpxSrc -> Display_Grpx
       pObj->GrpxSrcPrm.outQueParams.nextLink = pObj->Display_GrpxLinkID;
       pObj->Display_GrpxPrm.inQueParams.prevLinkId = pObj->GrpxSrcLinkID;
       pObj->Display_GrpxPrm.inQueParams.prevLinkQueId = 0;

}

Int32 chains_lvdsVipMultiCam_Sgx3Dsrv_Create(chains_lvdsVipMultiCam_Sgx3DsrvObj *pObj, Void *appObj){

       Int32 status;

       chains_lvdsVipMultiCam_Sgx3Dsrv_SetLinkId(pObj);
       chains_lvdsVipMultiCam_Sgx3Dsrv_ResetLinkPrms(pObj);

       chains_lvdsVipMultiCam_Sgx3Dsrv_SetPrms(pObj);
       chains_lvdsVipMultiCam_Sgx3Dsrv_SetAppPrms(pObj, appObj);

       chains_lvdsVipMultiCam_Sgx3Dsrv_ConnectLinks(pObj);
       status = System_linkCreate(pObj->CaptureLinkID, &pObj->CapturePrm, sizeof(pObj->CapturePrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Dup_sv_orgLinkID, &pObj->Dup_sv_orgPrm, sizeof(pObj->Dup_sv_orgPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->SyncLinkID, &pObj->SyncPrm, sizeof(pObj->SyncPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Dup_svLinkID, &pObj->Dup_svPrm, sizeof(pObj->Dup_svPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_IPU1_0_A15_0_2LinkID, &pObj->IPCOut_IPU1_0_A15_0_2Prm, sizeof(pObj->IPCOut_IPU1_0_A15_0_2Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_A15_0_IPU1_0_0LinkID, &pObj->IPCIn_A15_0_IPU1_0_0Prm, sizeof(pObj->IPCIn_A15_0_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_IPU1_0_DSP1_1LinkID, &pObj->IPCOut_IPU1_0_DSP1_1Prm, sizeof(pObj->IPCOut_IPU1_0_DSP1_1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_DSP1_IPU1_0_1LinkID, &pObj->IPCIn_DSP1_IPU1_0_1Prm, sizeof(pObj->IPCIn_DSP1_IPU1_0_1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_IPU1_0_DSP1_0LinkID, &pObj->IPCOut_IPU1_0_DSP1_0Prm, sizeof(pObj->IPCOut_IPU1_0_DSP1_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_DSP1_IPU1_0_0LinkID, &pObj->IPCIn_DSP1_IPU1_0_0Prm, sizeof(pObj->IPCIn_DSP1_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_GeoAlign3DLinkID, &pObj->Alg_GeoAlign3DPrm, sizeof(pObj->Alg_GeoAlign3DPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_DSP1_A15_0_1LinkID, &pObj->IPCOut_DSP1_A15_0_1Prm, sizeof(pObj->IPCOut_DSP1_A15_0_1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_A15_0_DSP1_2LinkID, &pObj->IPCIn_A15_0_DSP1_2Prm, sizeof(pObj->IPCIn_A15_0_DSP1_2Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_SynthesisLinkID, &pObj->Alg_SynthesisPrm, sizeof(pObj->Alg_SynthesisPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_DSP1_A15_0_2LinkID, &pObj->IPCOut_DSP1_A15_0_2Prm, sizeof(pObj->IPCOut_DSP1_A15_0_2Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_A15_0_DSP1_3LinkID, &pObj->IPCIn_A15_0_DSP1_3Prm, sizeof(pObj->IPCIn_A15_0_DSP1_3Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_PhotoAlignLinkID, &pObj->Alg_PhotoAlignPrm, sizeof(pObj->Alg_PhotoAlignPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_DSP1_A15_0_0LinkID, &pObj->IPCOut_DSP1_A15_0_0Prm, sizeof(pObj->IPCOut_DSP1_A15_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_A15_0_DSP1_1LinkID, &pObj->IPCIn_A15_0_DSP1_1Prm, sizeof(pObj->IPCIn_A15_0_DSP1_1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Sgx3DsrvLinkID, &pObj->Sgx3DsrvPrm, sizeof(pObj->Sgx3DsrvPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_A15_0_IPU1_0_0LinkID, &pObj->IPCOut_A15_0_IPU1_0_0Prm, sizeof(pObj->IPCOut_A15_0_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_IPU1_0_A15_0_0LinkID, &pObj->IPCIn_IPU1_0_A15_0_0Prm, sizeof(pObj->IPCIn_IPU1_0_A15_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Display_M4LinkID, &pObj->Display_M4Prm, sizeof(pObj->Display_M4Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->SelectLinkID, &pObj->SelectPrm, sizeof(pObj->SelectPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->VPE_sv_org2LinkID, &pObj->VPE_sv_org2Prm, sizeof(pObj->VPE_sv_org2Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Sync_sv_org2LinkID, &pObj->Sync_sv_org2Prm, sizeof(pObj->Sync_sv_org2Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_DmaSwMs_sv_org2LinkID, &pObj->Alg_DmaSwMs_sv_org2Prm, sizeof(pObj->Alg_DmaSwMs_sv_org2Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Display_sv_org2LinkID, &pObj->Display_sv_org2Prm, sizeof(pObj->Display_sv_org2Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->VPE_sv_org1LinkID, &pObj->VPE_sv_org1Prm, sizeof(pObj->VPE_sv_org1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Sync_sv_org1LinkID, &pObj->Sync_sv_org1Prm, sizeof(pObj->Sync_sv_org1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_DmaSwMs_sv_org1LinkID, &pObj->Alg_DmaSwMs_sv_org1Prm, sizeof(pObj->Alg_DmaSwMs_sv_org1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Display_sv_org1LinkID, &pObj->Display_sv_org1Prm, sizeof(pObj->Display_sv_org1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->NullLinkID, &pObj->NullPrm, sizeof(pObj->NullPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->GrpxSrcLinkID, &pObj->GrpxSrcPrm, sizeof(pObj->GrpxSrcPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Display_GrpxLinkID, &pObj->Display_GrpxPrm, sizeof(pObj->Display_GrpxPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_lvdsVipMultiCam_Sgx3Dsrv_Start(chains_lvdsVipMultiCam_Sgx3DsrvObj *pObj){

       Int32 status;

       status = System_linkStart(pObj->Display_GrpxLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->GrpxSrcLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->NullLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Display_sv_org1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_DmaSwMs_sv_org1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Sync_sv_org1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->VPE_sv_org1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Display_sv_org2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_DmaSwMs_sv_org2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Sync_sv_org2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->VPE_sv_org2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->SelectLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Display_M4LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_IPU1_0_A15_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_A15_0_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Sgx3DsrvLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_A15_0_DSP1_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_DSP1_A15_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_PhotoAlignLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_A15_0_DSP1_3LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_DSP1_A15_0_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_SynthesisLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_A15_0_DSP1_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_DSP1_A15_0_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_GeoAlign3DLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_DSP1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_IPU1_0_DSP1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_DSP1_IPU1_0_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_IPU1_0_DSP1_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_A15_0_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_IPU1_0_A15_0_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Dup_svLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->SyncLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Dup_sv_orgLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_lvdsVipMultiCam_Sgx3Dsrv_Stop(chains_lvdsVipMultiCam_Sgx3DsrvObj *pObj){

       Int32 status;

       status = System_linkStop(pObj->Display_GrpxLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->GrpxSrcLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->NullLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Display_sv_org1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_DmaSwMs_sv_org1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Sync_sv_org1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->VPE_sv_org1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Display_sv_org2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_DmaSwMs_sv_org2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Sync_sv_org2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->VPE_sv_org2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->SelectLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Display_M4LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_IPU1_0_A15_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_A15_0_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Sgx3DsrvLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_A15_0_DSP1_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_DSP1_A15_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_PhotoAlignLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_A15_0_DSP1_3LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_DSP1_A15_0_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_SynthesisLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_A15_0_DSP1_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_DSP1_A15_0_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_GeoAlign3DLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_DSP1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_IPU1_0_DSP1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_DSP1_IPU1_0_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_IPU1_0_DSP1_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_A15_0_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_IPU1_0_A15_0_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Dup_svLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->SyncLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Dup_sv_orgLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_lvdsVipMultiCam_Sgx3Dsrv_Delete(chains_lvdsVipMultiCam_Sgx3DsrvObj *pObj){

       Int32 status;

       status = System_linkDelete(pObj->Display_GrpxLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->GrpxSrcLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->NullLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Display_sv_org1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_DmaSwMs_sv_org1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Sync_sv_org1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->VPE_sv_org1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Display_sv_org2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_DmaSwMs_sv_org2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Sync_sv_org2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->VPE_sv_org2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->SelectLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Display_M4LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_IPU1_0_A15_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_A15_0_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Sgx3DsrvLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_A15_0_DSP1_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_DSP1_A15_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_PhotoAlignLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_A15_0_DSP1_3LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_DSP1_A15_0_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_SynthesisLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_A15_0_DSP1_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_DSP1_A15_0_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_GeoAlign3DLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_DSP1_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_IPU1_0_DSP1_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_DSP1_IPU1_0_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_IPU1_0_DSP1_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_A15_0_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_IPU1_0_A15_0_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Dup_svLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->SyncLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Dup_sv_orgLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Void chains_lvdsVipMultiCam_Sgx3Dsrv_printBufferStatistics(chains_lvdsVipMultiCam_Sgx3DsrvObj *pObj){
       System_linkPrintBufferStatistics(pObj->CaptureLinkID);
       System_linkPrintBufferStatistics(pObj->Dup_sv_orgLinkID);
       System_linkPrintBufferStatistics(pObj->SyncLinkID);
       System_linkPrintBufferStatistics(pObj->Dup_svLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_IPU1_0_A15_0_2LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_A15_0_IPU1_0_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCOut_IPU1_0_DSP1_1LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_DSP1_IPU1_0_1LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCOut_IPU1_0_DSP1_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_DSP1_IPU1_0_0LinkID);
       System_linkPrintBufferStatistics(pObj->Alg_GeoAlign3DLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_DSP1_A15_0_1LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_A15_0_DSP1_2LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->Alg_SynthesisLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_DSP1_A15_0_2LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_A15_0_DSP1_3LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->Alg_PhotoAlignLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_DSP1_A15_0_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_A15_0_DSP1_1LinkID);
       System_linkPrintBufferStatistics(pObj->Sgx3DsrvLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_A15_0_IPU1_0_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_IPU1_0_A15_0_0LinkID);
       System_linkPrintBufferStatistics(pObj->Display_M4LinkID);
       System_linkPrintBufferStatistics(pObj->SelectLinkID);
       System_linkPrintBufferStatistics(pObj->VPE_sv_org2LinkID);
       System_linkPrintBufferStatistics(pObj->Sync_sv_org2LinkID);
       System_linkPrintBufferStatistics(pObj->Alg_DmaSwMs_sv_org2LinkID);
       System_linkPrintBufferStatistics(pObj->Display_sv_org2LinkID);
       System_linkPrintBufferStatistics(pObj->VPE_sv_org1LinkID);
       System_linkPrintBufferStatistics(pObj->Sync_sv_org1LinkID);
       System_linkPrintBufferStatistics(pObj->Alg_DmaSwMs_sv_org1LinkID);
       System_linkPrintBufferStatistics(pObj->Display_sv_org1LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->NullLinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->GrpxSrcLinkID);
       System_linkPrintBufferStatistics(pObj->Display_GrpxLinkID);
       Task_sleep(500);
}

Void chains_lvdsVipMultiCam_Sgx3Dsrv_printStatistics(chains_lvdsVipMultiCam_Sgx3DsrvObj *pObj){
       System_linkPrintStatistics(pObj->CaptureLinkID);
       System_linkPrintStatistics(pObj->Dup_sv_orgLinkID);
       System_linkPrintStatistics(pObj->SyncLinkID);
       System_linkPrintStatistics(pObj->Dup_svLinkID);
       System_linkPrintStatistics(pObj->IPCOut_IPU1_0_A15_0_2LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_A15_0_IPU1_0_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCOut_IPU1_0_DSP1_1LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_DSP1_IPU1_0_1LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCOut_IPU1_0_DSP1_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_DSP1_IPU1_0_0LinkID);
       System_linkPrintStatistics(pObj->Alg_GeoAlign3DLinkID);
       System_linkPrintStatistics(pObj->IPCOut_DSP1_A15_0_1LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_A15_0_DSP1_2LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->Alg_SynthesisLinkID);
       System_linkPrintStatistics(pObj->IPCOut_DSP1_A15_0_2LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_A15_0_DSP1_3LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->Alg_PhotoAlignLinkID);
       System_linkPrintStatistics(pObj->IPCOut_DSP1_A15_0_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_A15_0_DSP1_1LinkID);
       System_linkPrintStatistics(pObj->Sgx3DsrvLinkID);
       System_linkPrintStatistics(pObj->IPCOut_A15_0_IPU1_0_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_IPU1_0_A15_0_0LinkID);
       System_linkPrintStatistics(pObj->Display_M4LinkID);
       System_linkPrintStatistics(pObj->SelectLinkID);
       System_linkPrintStatistics(pObj->VPE_sv_org2LinkID);
       System_linkPrintStatistics(pObj->Sync_sv_org2LinkID);
       System_linkPrintStatistics(pObj->Alg_DmaSwMs_sv_org2LinkID);
       System_linkPrintStatistics(pObj->Display_sv_org2LinkID);
       System_linkPrintStatistics(pObj->VPE_sv_org1LinkID);
       System_linkPrintStatistics(pObj->Sync_sv_org1LinkID);
       System_linkPrintStatistics(pObj->Alg_DmaSwMs_sv_org1LinkID);
       System_linkPrintStatistics(pObj->Display_sv_org1LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->NullLinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->GrpxSrcLinkID);
       System_linkPrintStatistics(pObj->Display_GrpxLinkID);
       Task_sleep(500);
}

