/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/
#include "chains_lvdsVip3dSurroundView_priv.h"
Void chains_lvdsVip3dSurroundView_SetLinkId(chains_lvdsVip3dSurroundViewObj *pObj){
       pObj->CaptureLinkID                  = SYSTEM_LINK_ID_CAPTURE_0;
       pObj->SyncLinkID                     = IPU1_0_LINK (SYSTEM_LINK_ID_SYNC_0);
       pObj->Dup_svLinkID                   = IPU1_0_LINK (SYSTEM_LINK_ID_DUP_0);
       pObj->IPCOut_IPU1_0_A15_0_2LinkID    = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_OUT_2);
       pObj->IPCIn_A15_0_IPU1_0_0LinkID     = A15_0_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->EpSink_1LinkID                 = SYSTEM_LINK_ID_EP_0;
       pObj->IPCOut_IPU1_0_DSP2_1LinkID     = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_OUT_1);
       pObj->IPCIn_DSP2_IPU1_0_1LinkID      = DSP2_LINK (SYSTEM_LINK_ID_IPC_IN_1);
       pObj->IPCOut_IPU1_0_DSP2_0LinkID     = IPU1_0_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_DSP2_IPU1_0_0LinkID      = DSP2_LINK (SYSTEM_LINK_ID_IPC_IN_0);
       pObj->Alg_GeoAlign3DLinkID           = DSP2_LINK (SYSTEM_LINK_ID_ALG_0);
       pObj->IPCOut_DSP2_A15_0_1LinkID      = DSP2_LINK (SYSTEM_LINK_ID_IPC_OUT_1);
       pObj->IPCIn_A15_0_DSP2_2LinkID       = A15_0_LINK (SYSTEM_LINK_ID_IPC_IN_2);
       pObj->Alg_SynthesisLinkID            = DSP2_LINK (SYSTEM_LINK_ID_ALG_1);
       pObj->IPCOut_DSP2_A15_0_0LinkID      = DSP2_LINK (SYSTEM_LINK_ID_IPC_OUT_0);
       pObj->IPCIn_A15_0_DSP2_1LinkID       = A15_0_LINK (SYSTEM_LINK_ID_IPC_IN_1);
       pObj->Alg_PhotoAlignLinkID           = DSP2_LINK (SYSTEM_LINK_ID_ALG_2);
       pObj->IPCOut_DSP2_A15_0_2LinkID      = DSP2_LINK (SYSTEM_LINK_ID_IPC_OUT_2);
       pObj->IPCIn_A15_0_DSP2_3LinkID       = A15_0_LINK (SYSTEM_LINK_ID_IPC_IN_3);
       pObj->srv3dLinkID                 = A15_0_LINK (SYSTEM_LINK_ID_MERGE_0);
       pObj->EpSink_2LinkID                 = SYSTEM_LINK_ID_EP_1;
       pObj->NullLinkID                     = DSP2_LINK (SYSTEM_LINK_ID_NULL_0);
}

Void chains_lvdsVip3dSurroundView_ResetLinkPrms(chains_lvdsVip3dSurroundViewObj *pObj){
       CaptureLink_CreateParams_Init(&pObj->CapturePrm);
       SyncLink_CreateParams_Init(&pObj->SyncPrm);
       DupLink_CreateParams_Init(&pObj->Dup_svPrm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_IPU1_0_A15_0_2Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_A15_0_IPU1_0_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_IPU1_0_DSP2_1Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_DSP2_IPU1_0_1Prm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_IPU1_0_DSP2_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_DSP2_IPU1_0_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_DSP2_A15_0_1Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_A15_0_DSP2_2Prm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_DSP2_A15_0_0Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_A15_0_DSP2_1Prm);
       IpcLink_CreateParams_Init(&pObj->IPCOut_DSP2_A15_0_2Prm);
       IpcLink_CreateParams_Init(&pObj->IPCIn_A15_0_DSP2_3Prm);
       MergeLink_CreateParams_Init(&pObj->srv3dPrm);
       NullLink_CreateParams_Init (&pObj->NullPrm);
}

Void chains_lvdsVip3dSurroundView_SetPrms(chains_lvdsVip3dSurroundViewObj *pObj){
       (pObj->Dup_svPrm).numOutQue = 3;
       (pObj->Alg_GeoAlign3DPrm).baseClassCreate.size  = sizeof(AlgorithmLink_GAlign3DCreateParams);
       (pObj->Alg_GeoAlign3DPrm).baseClassCreate.algId  = ALGORITHM_LINK_DSP_ALG_GALIGNMENT_3D;
       (pObj->Alg_SynthesisPrm).baseClassCreate.size  = sizeof(AlgorithmLink_SynthesisCreateParams);
       (pObj->Alg_SynthesisPrm).baseClassCreate.algId  = ALGORITHM_LINK_DSP_ALG_SYNTHESIS;
       (pObj->Alg_PhotoAlignPrm).baseClassCreate.size  = sizeof(AlgorithmLink_PAlignCreateParams);
       (pObj->Alg_PhotoAlignPrm).baseClassCreate.algId  = ALGORITHM_LINK_DSP_ALG_PALIGNMENT;
       (pObj->srv3dPrm).numInQue = 3;
       (pObj->NullPrm).numInQue = 1;
}

Void chains_lvdsVip3dSurroundView_ConnectLinks(chains_lvdsVip3dSurroundViewObj *pObj){

       //Capture -> Sync
       pObj->CapturePrm.outQueParams.nextLink = pObj->SyncLinkID;
       pObj->SyncPrm.inQueParams.prevLinkId = pObj->CaptureLinkID;
       pObj->SyncPrm.inQueParams.prevLinkQueId = 0;

       //Sync -> Dup_sv
       pObj->SyncPrm.outQueParams.nextLink = pObj->Dup_svLinkID;
       pObj->Dup_svPrm.inQueParams.prevLinkId = pObj->SyncLinkID;
       pObj->Dup_svPrm.inQueParams.prevLinkQueId = 0;

       //Dup_sv -> IPCOut_IPU1_0_DSP2_0
       pObj->Dup_svPrm.outQueParams[0].nextLink = pObj->IPCOut_IPU1_0_DSP2_0LinkID;
       pObj->IPCOut_IPU1_0_DSP2_0Prm.inQueParams.prevLinkId = pObj->Dup_svLinkID;
       pObj->IPCOut_IPU1_0_DSP2_0Prm.inQueParams.prevLinkQueId = 0;

       //Dup_sv -> IPCOut_IPU1_0_DSP2_1
       pObj->Dup_svPrm.outQueParams[1].nextLink = pObj->IPCOut_IPU1_0_DSP2_1LinkID;
       pObj->IPCOut_IPU1_0_DSP2_1Prm.inQueParams.prevLinkId = pObj->Dup_svLinkID;
       pObj->IPCOut_IPU1_0_DSP2_1Prm.inQueParams.prevLinkQueId = 1;

       //Dup_sv -> IPCOut_IPU1_0_A15_0_2
       pObj->Dup_svPrm.outQueParams[2].nextLink = pObj->IPCOut_IPU1_0_A15_0_2LinkID;
       pObj->IPCOut_IPU1_0_A15_0_2Prm.inQueParams.prevLinkId = pObj->Dup_svLinkID;
       pObj->IPCOut_IPU1_0_A15_0_2Prm.inQueParams.prevLinkQueId = 2;

       //IPCOut_IPU1_0_A15_0_2 -> IPCIn_A15_0_IPU1_0_0
       pObj->IPCOut_IPU1_0_A15_0_2Prm.outQueParams.nextLink = pObj->IPCIn_A15_0_IPU1_0_0LinkID;
       pObj->IPCIn_A15_0_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->IPCOut_IPU1_0_A15_0_2LinkID;
       pObj->IPCIn_A15_0_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_A15_0_IPU1_0_0 -> EpSink_1
       pObj->IPCIn_A15_0_IPU1_0_0Prm.outQueParams.nextLink = pObj->EpSink_1LinkID;
       pObj->EpSink_1Prm.inQueParams.prevLinkId = pObj->IPCIn_A15_0_IPU1_0_0LinkID;
       pObj->EpSink_1Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_IPU1_0_DSP2_1 -> IPCIn_DSP2_IPU1_0_1
       pObj->IPCOut_IPU1_0_DSP2_1Prm.outQueParams.nextLink = pObj->IPCIn_DSP2_IPU1_0_1LinkID;
       pObj->IPCIn_DSP2_IPU1_0_1Prm.inQueParams.prevLinkId = pObj->IPCOut_IPU1_0_DSP2_1LinkID;
       pObj->IPCIn_DSP2_IPU1_0_1Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_DSP2_IPU1_0_1 -> Alg_Synthesis
       pObj->IPCIn_DSP2_IPU1_0_1Prm.outQueParams.nextLink = pObj->Alg_SynthesisLinkID;
       pObj->Alg_SynthesisPrm.inQueParams[0].prevLinkId = pObj->IPCIn_DSP2_IPU1_0_1LinkID;
       pObj->Alg_SynthesisPrm.inQueParams[0].prevLinkQueId = 0;

       //IPCOut_IPU1_0_DSP2_0 -> IPCIn_DSP2_IPU1_0_0
       pObj->IPCOut_IPU1_0_DSP2_0Prm.outQueParams.nextLink = pObj->IPCIn_DSP2_IPU1_0_0LinkID;
       pObj->IPCIn_DSP2_IPU1_0_0Prm.inQueParams.prevLinkId = pObj->IPCOut_IPU1_0_DSP2_0LinkID;
       pObj->IPCIn_DSP2_IPU1_0_0Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_DSP2_IPU1_0_0 -> Alg_GeoAlign3D
       pObj->IPCIn_DSP2_IPU1_0_0Prm.outQueParams.nextLink = pObj->Alg_GeoAlign3DLinkID;
       pObj->Alg_GeoAlign3DPrm.inQueParams[0].prevLinkId = pObj->IPCIn_DSP2_IPU1_0_0LinkID;
       pObj->Alg_GeoAlign3DPrm.inQueParams[0].prevLinkQueId = 0;

       //Alg_GeoAlign3D -> Alg_Synthesis
       pObj->Alg_GeoAlign3DPrm.outQueParams[0].nextLink = pObj->Alg_SynthesisLinkID;
       pObj->Alg_SynthesisPrm.inQueParams[1].prevLinkId = pObj->Alg_GeoAlign3DLinkID;
       pObj->Alg_SynthesisPrm.inQueParams[1].prevLinkQueId = 0;

       //Alg_GeoAlign3D -> IPCOut_DSP2_A15_0_1
       pObj->Alg_GeoAlign3DPrm.outQueParams[1].nextLink = pObj->IPCOut_DSP2_A15_0_1LinkID;
       pObj->IPCOut_DSP2_A15_0_1Prm.inQueParams.prevLinkId = pObj->Alg_GeoAlign3DLinkID;
       pObj->IPCOut_DSP2_A15_0_1Prm.inQueParams.prevLinkQueId = 1;

       //IPCOut_DSP2_A15_0_1 -> IPCIn_A15_0_DSP2_2
       pObj->IPCOut_DSP2_A15_0_1Prm.outQueParams.nextLink = pObj->IPCIn_A15_0_DSP2_2LinkID;
       pObj->IPCIn_A15_0_DSP2_2Prm.inQueParams.prevLinkId = pObj->IPCOut_DSP2_A15_0_1LinkID;
       pObj->IPCIn_A15_0_DSP2_2Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_A15_0_DSP2_2 -> srv3d
       pObj->IPCIn_A15_0_DSP2_2Prm.outQueParams.nextLink = pObj->srv3dLinkID;
       pObj->srv3dPrm.inQueParams[1].prevLinkId = pObj->IPCIn_A15_0_DSP2_2LinkID;
       pObj->srv3dPrm.inQueParams[1].prevLinkQueId = 0;

       //Alg_Synthesis -> Null
       pObj->Alg_SynthesisPrm.outQueParams[0].nextLink = pObj->NullLinkID;
       pObj->NullPrm.inQueParams[0].prevLinkId = pObj->Alg_SynthesisLinkID;
       pObj->NullPrm.inQueParams[0].prevLinkQueId = 0;

       //Alg_Synthesis -> Alg_PhotoAlign
       pObj->Alg_SynthesisPrm.outQueParams[1].nextLink = pObj->Alg_PhotoAlignLinkID;
       pObj->Alg_PhotoAlignPrm.inQueParams[0].prevLinkId = pObj->Alg_SynthesisLinkID;
       pObj->Alg_PhotoAlignPrm.inQueParams[0].prevLinkQueId = 1;

       //Alg_Synthesis -> IPCOut_DSP2_A15_0_0
       pObj->Alg_SynthesisPrm.outQueParams[2].nextLink = pObj->IPCOut_DSP2_A15_0_0LinkID;
       pObj->IPCOut_DSP2_A15_0_0Prm.inQueParams.prevLinkId = pObj->Alg_SynthesisLinkID;
       pObj->IPCOut_DSP2_A15_0_0Prm.inQueParams.prevLinkQueId = 2;

       //IPCOut_DSP2_A15_0_0 -> IPCIn_A15_0_DSP2_1
       pObj->IPCOut_DSP2_A15_0_0Prm.outQueParams.nextLink = pObj->IPCIn_A15_0_DSP2_1LinkID;
       pObj->IPCIn_A15_0_DSP2_1Prm.inQueParams.prevLinkId = pObj->IPCOut_DSP2_A15_0_0LinkID;
       pObj->IPCIn_A15_0_DSP2_1Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_A15_0_DSP2_1 -> srv3d
       pObj->IPCIn_A15_0_DSP2_1Prm.outQueParams.nextLink = pObj->srv3dLinkID;
       pObj->srv3dPrm.inQueParams[0].prevLinkId = pObj->IPCIn_A15_0_DSP2_1LinkID;
       pObj->srv3dPrm.inQueParams[0].prevLinkQueId = 0;

       //Alg_PhotoAlign -> IPCOut_DSP2_A15_0_2
       pObj->Alg_PhotoAlignPrm.outQueParams[0].nextLink = pObj->IPCOut_DSP2_A15_0_2LinkID;
       pObj->IPCOut_DSP2_A15_0_2Prm.inQueParams.prevLinkId = pObj->Alg_PhotoAlignLinkID;
       pObj->IPCOut_DSP2_A15_0_2Prm.inQueParams.prevLinkQueId = 0;

       //IPCOut_DSP2_A15_0_2 -> IPCIn_A15_0_DSP2_3
       pObj->IPCOut_DSP2_A15_0_2Prm.outQueParams.nextLink = pObj->IPCIn_A15_0_DSP2_3LinkID;
       pObj->IPCIn_A15_0_DSP2_3Prm.inQueParams.prevLinkId = pObj->IPCOut_DSP2_A15_0_2LinkID;
       pObj->IPCIn_A15_0_DSP2_3Prm.inQueParams.prevLinkQueId = 0;

       //IPCIn_A15_0_DSP2_3 -> srv3d
       pObj->IPCIn_A15_0_DSP2_3Prm.outQueParams.nextLink = pObj->srv3dLinkID;
       pObj->srv3dPrm.inQueParams[2].prevLinkId = pObj->IPCIn_A15_0_DSP2_3LinkID;
       pObj->srv3dPrm.inQueParams[2].prevLinkQueId = 0;

       //srv3d -> EpSink_2
       pObj->srv3dPrm.outQueParams.nextLink = pObj->EpSink_2LinkID;
       pObj->EpSink_2Prm.inQueParams.prevLinkId = pObj->srv3dLinkID;
       pObj->EpSink_2Prm.inQueParams.prevLinkQueId = 0;

}

Int32 chains_lvdsVip3dSurroundView_Create(chains_lvdsVip3dSurroundViewObj *pObj, Void *appObj){

       Int32 status;

       chains_lvdsVip3dSurroundView_SetLinkId(pObj);
       chains_lvdsVip3dSurroundView_ResetLinkPrms(pObj);

       chains_lvdsVip3dSurroundView_SetPrms(pObj);
       chains_lvdsVip3dSurroundView_SetAppPrms(pObj, appObj);

       chains_lvdsVip3dSurroundView_ConnectLinks(pObj);
       status = System_linkCreate(pObj->CaptureLinkID, &pObj->CapturePrm, sizeof(pObj->CapturePrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->SyncLinkID, &pObj->SyncPrm, sizeof(pObj->SyncPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Dup_svLinkID, &pObj->Dup_svPrm, sizeof(pObj->Dup_svPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_IPU1_0_A15_0_2LinkID, &pObj->IPCOut_IPU1_0_A15_0_2Prm, sizeof(pObj->IPCOut_IPU1_0_A15_0_2Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_A15_0_IPU1_0_0LinkID, &pObj->IPCIn_A15_0_IPU1_0_0Prm, sizeof(pObj->IPCIn_A15_0_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->EpSink_1LinkID, &pObj->EpSink_1Prm, sizeof(pObj->EpSink_1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_IPU1_0_DSP2_1LinkID, &pObj->IPCOut_IPU1_0_DSP2_1Prm, sizeof(pObj->IPCOut_IPU1_0_DSP2_1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_DSP2_IPU1_0_1LinkID, &pObj->IPCIn_DSP2_IPU1_0_1Prm, sizeof(pObj->IPCIn_DSP2_IPU1_0_1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_IPU1_0_DSP2_0LinkID, &pObj->IPCOut_IPU1_0_DSP2_0Prm, sizeof(pObj->IPCOut_IPU1_0_DSP2_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_DSP2_IPU1_0_0LinkID, &pObj->IPCIn_DSP2_IPU1_0_0Prm, sizeof(pObj->IPCIn_DSP2_IPU1_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_GeoAlign3DLinkID, &pObj->Alg_GeoAlign3DPrm, sizeof(pObj->Alg_GeoAlign3DPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_DSP2_A15_0_1LinkID, &pObj->IPCOut_DSP2_A15_0_1Prm, sizeof(pObj->IPCOut_DSP2_A15_0_1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_A15_0_DSP2_2LinkID, &pObj->IPCIn_A15_0_DSP2_2Prm, sizeof(pObj->IPCIn_A15_0_DSP2_2Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_SynthesisLinkID, &pObj->Alg_SynthesisPrm, sizeof(pObj->Alg_SynthesisPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_DSP2_A15_0_0LinkID, &pObj->IPCOut_DSP2_A15_0_0Prm, sizeof(pObj->IPCOut_DSP2_A15_0_0Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_A15_0_DSP2_1LinkID, &pObj->IPCIn_A15_0_DSP2_1Prm, sizeof(pObj->IPCIn_A15_0_DSP2_1Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_PhotoAlignLinkID, &pObj->Alg_PhotoAlignPrm, sizeof(pObj->Alg_PhotoAlignPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCOut_DSP2_A15_0_2LinkID, &pObj->IPCOut_DSP2_A15_0_2Prm, sizeof(pObj->IPCOut_DSP2_A15_0_2Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->IPCIn_A15_0_DSP2_3LinkID, &pObj->IPCIn_A15_0_DSP2_3Prm, sizeof(pObj->IPCIn_A15_0_DSP2_3Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->srv3dLinkID, &pObj->srv3dPrm, sizeof(pObj->srv3dPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->EpSink_2LinkID, &pObj->EpSink_2Prm, sizeof(pObj->EpSink_2Prm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->NullLinkID, &pObj->NullPrm, sizeof(pObj->NullPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_lvdsVip3dSurroundView_Start(chains_lvdsVip3dSurroundViewObj *pObj){

       Int32 status;

       status = System_linkStart(pObj->NullLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->EpSink_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->srv3dLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_A15_0_DSP2_3LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_DSP2_A15_0_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_PhotoAlignLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_A15_0_DSP2_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_DSP2_A15_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_SynthesisLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_A15_0_DSP2_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_DSP2_A15_0_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_GeoAlign3DLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_DSP2_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_IPU1_0_DSP2_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_DSP2_IPU1_0_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_IPU1_0_DSP2_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->EpSink_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCIn_A15_0_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->IPCOut_IPU1_0_A15_0_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Dup_svLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->SyncLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_lvdsVip3dSurroundView_Stop(chains_lvdsVip3dSurroundViewObj *pObj){

       Int32 status;

       status = System_linkStop(pObj->NullLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->EpSink_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->srv3dLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_A15_0_DSP2_3LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_DSP2_A15_0_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_PhotoAlignLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_A15_0_DSP2_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_DSP2_A15_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_SynthesisLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_A15_0_DSP2_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_DSP2_A15_0_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_GeoAlign3DLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_DSP2_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_IPU1_0_DSP2_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_DSP2_IPU1_0_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_IPU1_0_DSP2_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->EpSink_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCIn_A15_0_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->IPCOut_IPU1_0_A15_0_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Dup_svLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->SyncLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_lvdsVip3dSurroundView_Delete(chains_lvdsVip3dSurroundViewObj *pObj){

       Int32 status;

       status = System_linkDelete(pObj->NullLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->EpSink_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->srv3dLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_A15_0_DSP2_3LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_DSP2_A15_0_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_PhotoAlignLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_A15_0_DSP2_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_DSP2_A15_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_SynthesisLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_A15_0_DSP2_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_DSP2_A15_0_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_GeoAlign3DLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_DSP2_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_IPU1_0_DSP2_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_DSP2_IPU1_0_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_IPU1_0_DSP2_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->EpSink_1LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCIn_A15_0_IPU1_0_0LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->IPCOut_IPU1_0_A15_0_2LinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Dup_svLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->SyncLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Void chains_lvdsVip3dSurroundView_printBufferStatistics(chains_lvdsVip3dSurroundViewObj *pObj){
       System_linkPrintBufferStatistics(pObj->CaptureLinkID);
       System_linkPrintBufferStatistics(pObj->SyncLinkID);
       System_linkPrintBufferStatistics(pObj->Dup_svLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_IPU1_0_A15_0_2LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_A15_0_IPU1_0_0LinkID);
       System_linkPrintBufferStatistics(pObj->EpSink_1LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCOut_IPU1_0_DSP2_1LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_DSP2_IPU1_0_1LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCOut_IPU1_0_DSP2_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_DSP2_IPU1_0_0LinkID);
       System_linkPrintBufferStatistics(pObj->Alg_GeoAlign3DLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_DSP2_A15_0_1LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_A15_0_DSP2_2LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->Alg_SynthesisLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_DSP2_A15_0_0LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_A15_0_DSP2_1LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->Alg_PhotoAlignLinkID);
       System_linkPrintBufferStatistics(pObj->IPCOut_DSP2_A15_0_2LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->IPCIn_A15_0_DSP2_3LinkID);
       System_linkPrintBufferStatistics(pObj->srv3dLinkID);
       System_linkPrintBufferStatistics(pObj->EpSink_2LinkID);
       Task_sleep(500);
       System_linkPrintBufferStatistics(pObj->NullLinkID);
       Task_sleep(500);
}

Void chains_lvdsVip3dSurroundView_printStatistics(chains_lvdsVip3dSurroundViewObj *pObj){
       System_linkPrintStatistics(pObj->CaptureLinkID);
       System_linkPrintStatistics(pObj->SyncLinkID);
       System_linkPrintStatistics(pObj->Dup_svLinkID);
       System_linkPrintStatistics(pObj->IPCOut_IPU1_0_A15_0_2LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_A15_0_IPU1_0_0LinkID);
       System_linkPrintStatistics(pObj->EpSink_1LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCOut_IPU1_0_DSP2_1LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_DSP2_IPU1_0_1LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCOut_IPU1_0_DSP2_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_DSP2_IPU1_0_0LinkID);
       System_linkPrintStatistics(pObj->Alg_GeoAlign3DLinkID);
       System_linkPrintStatistics(pObj->IPCOut_DSP2_A15_0_1LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_A15_0_DSP2_2LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->Alg_SynthesisLinkID);
       System_linkPrintStatistics(pObj->IPCOut_DSP2_A15_0_0LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_A15_0_DSP2_1LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->Alg_PhotoAlignLinkID);
       System_linkPrintStatistics(pObj->IPCOut_DSP2_A15_0_2LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->IPCIn_A15_0_DSP2_3LinkID);
       System_linkPrintStatistics(pObj->srv3dLinkID);
       System_linkPrintStatistics(pObj->EpSink_2LinkID);
       Task_sleep(500);
       System_linkPrintStatistics(pObj->NullLinkID);
       Task_sleep(500);
}

