/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/

#ifndef _chains_vipSingleCameraTlr_H_
#define _chains_vipSingleCameraTlr_H_

#include <include/link_api/system.h>
#include <include/link_api/captureLink.h>
#include <include/link_api/dupLink.h>
#include <include/link_api/algorithmLink_clr.h>
#include <include/link_api/ipcLink.h>
#include <include/link_api/mergeLink.h>
#include <include/link_api/syncLink.h>
#include <include/link_api/algorithmLink_objectDraw.h>
#include <include/link_api/grpxSrcLink.h>
#include <include/link_api/displayLink.h>

typedef struct {
       UInt32    CaptureLinkID;
       UInt32    Dup_captureLinkID;
       UInt32    IPCOut_IPU1_0_DSP1_0LinkID;
       UInt32    IPCIn_DSP1_IPU1_0_0LinkID;
       UInt32    Alg_ClrLinkID;
       UInt32    IPCOut_DSP1_IPU1_0_0LinkID;
       UInt32    IPCIn_IPU1_0_DSP1_0LinkID;
       UInt32    Merge_algLinkID;
       UInt32    Sync_algLinkID;
       UInt32    Alg_ObjectDrawLinkID;
       UInt32    Display_algLinkID;
       UInt32    GrpxSrcLinkID;
       UInt32    Display_GrpxLinkID;

       CaptureLink_CreateParams                CapturePrm;
       DupLink_CreateParams                    Dup_capturePrm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_DSP1_0Prm;
       IpcLink_CreateParams                    IPCIn_DSP1_IPU1_0_0Prm;
       AlgorithmLink_ClrCreateParams           Alg_ClrPrm;
       IpcLink_CreateParams                    IPCOut_DSP1_IPU1_0_0Prm;
       IpcLink_CreateParams                    IPCIn_IPU1_0_DSP1_0Prm;
       MergeLink_CreateParams                  Merge_algPrm;
       SyncLink_CreateParams                   Sync_algPrm;
       AlgorithmLink_ObjectDrawCreateParams    Alg_ObjectDrawPrm;
       DisplayLink_CreateParams                Display_algPrm;
       GrpxSrcLink_CreateParams                GrpxSrcPrm;
       DisplayLink_CreateParams                Display_GrpxPrm;
} chains_vipSingleCameraTlrObj;

Void chains_vipSingleCameraTlr_SetLinkId(chains_vipSingleCameraTlrObj *pObj);

Void chains_vipSingleCameraTlr_ResetLinkPrms(chains_vipSingleCameraTlrObj *pObj);

Void chains_vipSingleCameraTlr_SetPrms(chains_vipSingleCameraTlrObj *pObj);

Void chains_vipSingleCameraTlr_ConnectLinks(chains_vipSingleCameraTlrObj *pObj);

Int32 chains_vipSingleCameraTlr_Create(chains_vipSingleCameraTlrObj *pObj, Void *appObj);

Int32 chains_vipSingleCameraTlr_Start(chains_vipSingleCameraTlrObj *pObj);

Int32 chains_vipSingleCameraTlr_Stop(chains_vipSingleCameraTlrObj *pObj);

Int32 chains_vipSingleCameraTlr_Delete(chains_vipSingleCameraTlrObj *pObj);

Void chains_vipSingleCameraTlr_printBufferStatistics(chains_vipSingleCameraTlrObj *pObj);

Void chains_vipSingleCameraTlr_printStatistics(chains_vipSingleCameraTlrObj *pObj);

Void chains_vipSingleCameraTlr_SetAppPrms(chains_vipSingleCameraTlrObj *pObj, Void *appObj);

#endif /* _chains_vipSingleCameraTlr_H_ */
