/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/

#ifndef _chains_srvCalibration_Display_tda3x_H_
#define _chains_srvCalibration_Display_tda3x_H_

#include <include/link_api/system.h>
#include <include/link_api/issCaptureLink.h>
#include <include/link_api/issM2mIspLink.h>
#include <include/link_api/algorithmLink_issAewb.h>
#include <include/link_api/dupLink.h>
#include <include/link_api/vpeLink.h>
#include <include/link_api/syncLink.h>
#include <include/link_api/algorithmLink_dmaSwMs.h>
#include <include/link_api/grpxSrcLink.h>
#include <include/link_api/displayLink.h>
#include <include/link_api/captureLink.h>
#include <include/link_api/nullLink.h>

typedef struct {
       UInt32    IssCaptureLinkID;
       UInt32    IssM2mIspLinkID;
       UInt32    Alg_IssAewbLinkID;
       UInt32    DupLinkID;
       UInt32    Null_ispLinkID;
       UInt32    VPELinkID;
       UInt32    SyncLinkID;
       UInt32    Alg_DmaSwMsLinkID;
       UInt32    DisplayLinkID;
       UInt32    GrpxSrcLinkID;
       UInt32    Display_GrpxLinkID;
       UInt32    Capture_dsswbLinkID;
       UInt32    Null_disWbLinkID;

       IssCaptureLink_CreateParams             IssCapturePrm;
       IssM2mIspLink_CreateParams              IssM2mIspPrm;
       AlgorithmLink_IssAewbCreateParams       Alg_IssAewbPrm;
       DupLink_CreateParams                    DupPrm;
       NullLink_CreateParams                   Null_ispPrm;
       VpeLink_CreateParams                    VPEPrm;
       SyncLink_CreateParams                   SyncPrm;
       AlgorithmLink_DmaSwMsCreateParams       Alg_DmaSwMsPrm;
       DisplayLink_CreateParams                DisplayPrm;
       GrpxSrcLink_CreateParams                GrpxSrcPrm;
       DisplayLink_CreateParams                Display_GrpxPrm;
       CaptureLink_CreateParams                Capture_dsswbPrm;
       NullLink_CreateParams                   Null_disWbPrm;
} chains_srvCalibration_Display_tda3xObj;

Void chains_srvCalibration_Display_tda3x_SetLinkId(chains_srvCalibration_Display_tda3xObj *pObj);

Void chains_srvCalibration_Display_tda3x_ResetLinkPrms(chains_srvCalibration_Display_tda3xObj *pObj);

Void chains_srvCalibration_Display_tda3x_SetPrms(chains_srvCalibration_Display_tda3xObj *pObj);

Void chains_srvCalibration_Display_tda3x_ConnectLinks(chains_srvCalibration_Display_tda3xObj *pObj);

Int32 chains_srvCalibration_Display_tda3x_Create(chains_srvCalibration_Display_tda3xObj *pObj, Void *appObj);

Int32 chains_srvCalibration_Display_tda3x_Start(chains_srvCalibration_Display_tda3xObj *pObj);

Int32 chains_srvCalibration_Display_tda3x_Stop(chains_srvCalibration_Display_tda3xObj *pObj);

Int32 chains_srvCalibration_Display_tda3x_Delete(chains_srvCalibration_Display_tda3xObj *pObj);

Void chains_srvCalibration_Display_tda3x_printBufferStatistics(chains_srvCalibration_Display_tda3xObj *pObj);

Void chains_srvCalibration_Display_tda3x_printStatistics(chains_srvCalibration_Display_tda3xObj *pObj);

Void chains_srvCalibration_Display_tda3x_SetAppPrms(chains_srvCalibration_Display_tda3xObj *pObj, Void *appObj);

#endif /* _chains_srvCalibration_Display_tda3x_H_ */
