/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/

#ifndef _chains_srvCalibration_Display_tda2x_H_
#define _chains_srvCalibration_Display_tda2x_H_

#include <include/link_api/system.h>
#include <include/link_api/dupLink.h>
#include <include/link_api/vpeLink.h>
#include <include/link_api/syncLink.h>
#include <include/link_api/algorithmLink_dmaSwMs.h>
#include <include/link_api/grpxSrcLink.h>
#include <include/link_api/displayLink.h>
#include <include/link_api/captureLink.h>
#include <include/link_api/nullLink.h>

typedef struct {
       UInt32    CaptureLinkID;
       UInt32    DupLinkID;
       UInt32    Null_captureLinkID;
       UInt32    VPELinkID;
       UInt32    SyncLinkID;
       UInt32    Alg_DmaSwMsLinkID;
       UInt32    DisplayLinkID;
       UInt32    GrpxSrcLinkID;
       UInt32    Display_GrpxLinkID;
       UInt32    Capture_dsswbLinkID;
       UInt32    Null_disWbLinkID;

       CaptureLink_CreateParams                CapturePrm;
       DupLink_CreateParams                    DupPrm;
       NullLink_CreateParams                   Null_capturePrm;
       VpeLink_CreateParams                    VPEPrm;
       SyncLink_CreateParams                   SyncPrm;
       AlgorithmLink_DmaSwMsCreateParams       Alg_DmaSwMsPrm;
       DisplayLink_CreateParams                DisplayPrm;
       GrpxSrcLink_CreateParams                GrpxSrcPrm;
       DisplayLink_CreateParams                Display_GrpxPrm;
       CaptureLink_CreateParams                Capture_dsswbPrm;
       NullLink_CreateParams                   Null_disWbPrm;
} chains_srvCalibration_Display_tda2xObj;

Void chains_srvCalibration_Display_tda2x_SetLinkId(chains_srvCalibration_Display_tda2xObj *pObj);

Void chains_srvCalibration_Display_tda2x_ResetLinkPrms(chains_srvCalibration_Display_tda2xObj *pObj);

Void chains_srvCalibration_Display_tda2x_SetPrms(chains_srvCalibration_Display_tda2xObj *pObj);

Void chains_srvCalibration_Display_tda2x_ConnectLinks(chains_srvCalibration_Display_tda2xObj *pObj);

Int32 chains_srvCalibration_Display_tda2x_Create(chains_srvCalibration_Display_tda2xObj *pObj, Void *appObj);

Int32 chains_srvCalibration_Display_tda2x_Start(chains_srvCalibration_Display_tda2xObj *pObj);

Int32 chains_srvCalibration_Display_tda2x_Stop(chains_srvCalibration_Display_tda2xObj *pObj);

Int32 chains_srvCalibration_Display_tda2x_Delete(chains_srvCalibration_Display_tda2xObj *pObj);

Void chains_srvCalibration_Display_tda2x_printBufferStatistics(chains_srvCalibration_Display_tda2xObj *pObj);

Void chains_srvCalibration_Display_tda2x_printStatistics(chains_srvCalibration_Display_tda2xObj *pObj);

Void chains_srvCalibration_Display_tda2x_SetAppPrms(chains_srvCalibration_Display_tda2xObj *pObj, Void *appObj);

#endif /* _chains_srvCalibration_Display_tda2x_H_ */
