/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/

#ifndef _chains_vipSingleCameraOpenCLFrameCopy_H_
#define _chains_vipSingleCameraOpenCLFrameCopy_H_

#include <include/link_api/system.h>
#include <include/link_api/captureLink.h>
#include <include/link_api/algorithmLink_openClframeCopy.h>
#include <include/link_api/ipcLink.h>
#include <include/link_api/grpxSrcLink.h>
#include <include/link_api/displayLink.h>

typedef struct {
       UInt32    CaptureLinkID;
       UInt32    IPCOut_IPU1_0_A15_0_0LinkID;
       UInt32    IPCIn_A15_0_IPU1_0_0LinkID;
       UInt32    Alg_OpenCLFrameCopyLinkID;
       UInt32    IPCOut_A15_0_IPU1_0_0LinkID;
       UInt32    IPCIn_IPU1_0_A15_0_0LinkID;
       UInt32    Display_VideoLinkID;
       UInt32    GrpxSrcLinkID;
       UInt32    Display_GrpxLinkID;

       CaptureLink_CreateParams                CapturePrm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_A15_0_0Prm;
       IpcLink_CreateParams                    IPCIn_A15_0_IPU1_0_0Prm;
       AlgorithmLink_OpenCLFrameCopyCreateParams Alg_OpenCLFrameCopyPrm;
       IpcLink_CreateParams                    IPCOut_A15_0_IPU1_0_0Prm;
       IpcLink_CreateParams                    IPCIn_IPU1_0_A15_0_0Prm;
       DisplayLink_CreateParams                Display_VideoPrm;
       GrpxSrcLink_CreateParams                GrpxSrcPrm;
       DisplayLink_CreateParams                Display_GrpxPrm;
} chains_vipSingleCameraOpenCLFrameCopyObj;

Void chains_vipSingleCameraOpenCLFrameCopy_SetLinkId(chains_vipSingleCameraOpenCLFrameCopyObj *pObj);

Void chains_vipSingleCameraOpenCLFrameCopy_ResetLinkPrms(chains_vipSingleCameraOpenCLFrameCopyObj *pObj);

Void chains_vipSingleCameraOpenCLFrameCopy_SetPrms(chains_vipSingleCameraOpenCLFrameCopyObj *pObj);

Void chains_vipSingleCameraOpenCLFrameCopy_ConnectLinks(chains_vipSingleCameraOpenCLFrameCopyObj *pObj);

Int32 chains_vipSingleCameraOpenCLFrameCopy_Create(chains_vipSingleCameraOpenCLFrameCopyObj *pObj, Void *appObj);

Int32 chains_vipSingleCameraOpenCLFrameCopy_Start(chains_vipSingleCameraOpenCLFrameCopyObj *pObj);

Int32 chains_vipSingleCameraOpenCLFrameCopy_Stop(chains_vipSingleCameraOpenCLFrameCopyObj *pObj);

Int32 chains_vipSingleCameraOpenCLFrameCopy_Delete(chains_vipSingleCameraOpenCLFrameCopyObj *pObj);

Void chains_vipSingleCameraOpenCLFrameCopy_printBufferStatistics(chains_vipSingleCameraOpenCLFrameCopyObj *pObj);

Void chains_vipSingleCameraOpenCLFrameCopy_printStatistics(chains_vipSingleCameraOpenCLFrameCopyObj *pObj);

Void chains_vipSingleCameraOpenCLFrameCopy_SetAppPrms(chains_vipSingleCameraOpenCLFrameCopyObj *pObj, Void *appObj);

#endif /* _chains_vipSingleCameraOpenCLFrameCopy_H_ */
