/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/

#ifndef _chains_avbRxDecodeDisplay_H_
#define _chains_avbRxDecodeDisplay_H_

#include <include/link_api/system.h>
#include <include/link_api/avbRxLink.h>
#include <include/link_api/decLink.h>
#include <include/link_api/syncLink.h>
#include <include/link_api/sgxFrmcpyLink.h>
#include <include/link_api/ipcLink.h>
#include <include/link_api/grpxSrcLink.h>
#include <include/link_api/displayLink.h>

typedef struct {
       UInt32    AvbRxLinkID;
       UInt32    DecodeLinkID;
       UInt32    Sync_svLinkID;
       UInt32    IPCOut_IPU1_0_A15_0_0LinkID;
       UInt32    IPCIn_A15_0_IPU1_0_0LinkID;
       UInt32    SgxFrmcpyLinkID;
       UInt32    IPCOut_A15_0_IPU1_0_0LinkID;
       UInt32    IPCIn_IPU1_0_A15_0_0LinkID;
       UInt32    Display_M4LinkID;
       UInt32    GrpxSrcLinkID;
       UInt32    Display_GrpxLinkID;

       AvbRxLink_CreateParams                  AvbRxPrm;
       DecLink_CreateParams                    DecodePrm;
       SyncLink_CreateParams                   Sync_svPrm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_A15_0_0Prm;
       IpcLink_CreateParams                    IPCIn_A15_0_IPU1_0_0Prm;
       SgxFrmcpyLink_CreateParams              SgxFrmcpyPrm;
       IpcLink_CreateParams                    IPCOut_A15_0_IPU1_0_0Prm;
       IpcLink_CreateParams                    IPCIn_IPU1_0_A15_0_0Prm;
       DisplayLink_CreateParams                Display_M4Prm;
       GrpxSrcLink_CreateParams                GrpxSrcPrm;
       DisplayLink_CreateParams                Display_GrpxPrm;
} chains_avbRxDecodeDisplayObj;

Void chains_avbRxDecodeDisplay_SetLinkId(chains_avbRxDecodeDisplayObj *pObj);

Void chains_avbRxDecodeDisplay_ResetLinkPrms(chains_avbRxDecodeDisplayObj *pObj);

Void chains_avbRxDecodeDisplay_SetPrms(chains_avbRxDecodeDisplayObj *pObj);

Void chains_avbRxDecodeDisplay_ConnectLinks(chains_avbRxDecodeDisplayObj *pObj);

Int32 chains_avbRxDecodeDisplay_Create(chains_avbRxDecodeDisplayObj *pObj, Void *appObj);

Int32 chains_avbRxDecodeDisplay_Start(chains_avbRxDecodeDisplayObj *pObj);

Int32 chains_avbRxDecodeDisplay_Stop(chains_avbRxDecodeDisplayObj *pObj);

Int32 chains_avbRxDecodeDisplay_Delete(chains_avbRxDecodeDisplayObj *pObj);

Void chains_avbRxDecodeDisplay_printBufferStatistics(chains_avbRxDecodeDisplayObj *pObj);

Void chains_avbRxDecodeDisplay_printStatistics(chains_avbRxDecodeDisplayObj *pObj);

Void chains_avbRxDecodeDisplay_SetAppPrms(chains_avbRxDecodeDisplayObj *pObj, Void *appObj);

#endif /* _chains_avbRxDecodeDisplay_H_ */
