/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/

#ifndef _chains_vipSingleCamFrmcpyEve_SgxDisplay_H_
#define _chains_vipSingleCamFrmcpyEve_SgxDisplay_H_

#include <include/link_api/system.h>
#include <include/link_api/captureLink.h>
#include <include/link_api/algorithmLink_frameCopy.h>
#include <include/link_api/sgxFrmcpyLink.h>
#include <include/link_api/ipcLink.h>
#include <include/link_api/grpxSrcLink.h>
#include <include/link_api/displayLink.h>

typedef struct {
       UInt32    CaptureLinkID;
       UInt32    IPCOut_IPU1_0_EVE1_0LinkID;
       UInt32    IPCIn_EVE1_IPU1_0_0LinkID;
       UInt32    Alg_FrameCopyLinkID;
       UInt32    IPCOut_EVE1_A15_0_0LinkID;
       UInt32    IPCIn_A15_0_EVE1_0LinkID;
       UInt32    SgxFrmcpyLinkID;
       UInt32    IPCOut_A15_0_IPU1_0_0LinkID;
       UInt32    IPCIn_IPU1_0_A15_0_0LinkID;
       UInt32    Display_M4LinkID;
       UInt32    GrpxSrcLinkID;
       UInt32    Display_GrpxLinkID;

       CaptureLink_CreateParams                CapturePrm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_EVE1_0Prm;
       IpcLink_CreateParams                    IPCIn_EVE1_IPU1_0_0Prm;
       AlgorithmLink_FrameCopyCreateParams     Alg_FrameCopyPrm;
       IpcLink_CreateParams                    IPCOut_EVE1_A15_0_0Prm;
       IpcLink_CreateParams                    IPCIn_A15_0_EVE1_0Prm;
       SgxFrmcpyLink_CreateParams              SgxFrmcpyPrm;
       IpcLink_CreateParams                    IPCOut_A15_0_IPU1_0_0Prm;
       IpcLink_CreateParams                    IPCIn_IPU1_0_A15_0_0Prm;
       DisplayLink_CreateParams                Display_M4Prm;
       GrpxSrcLink_CreateParams                GrpxSrcPrm;
       DisplayLink_CreateParams                Display_GrpxPrm;
} chains_vipSingleCamFrmcpyEve_SgxDisplayObj;

Void chains_vipSingleCamFrmcpyEve_SgxDisplay_SetLinkId(chains_vipSingleCamFrmcpyEve_SgxDisplayObj *pObj);

Void chains_vipSingleCamFrmcpyEve_SgxDisplay_ResetLinkPrms(chains_vipSingleCamFrmcpyEve_SgxDisplayObj *pObj);

Void chains_vipSingleCamFrmcpyEve_SgxDisplay_SetPrms(chains_vipSingleCamFrmcpyEve_SgxDisplayObj *pObj);

Void chains_vipSingleCamFrmcpyEve_SgxDisplay_ConnectLinks(chains_vipSingleCamFrmcpyEve_SgxDisplayObj *pObj);

Int32 chains_vipSingleCamFrmcpyEve_SgxDisplay_Create(chains_vipSingleCamFrmcpyEve_SgxDisplayObj *pObj, Void *appObj);

Int32 chains_vipSingleCamFrmcpyEve_SgxDisplay_Start(chains_vipSingleCamFrmcpyEve_SgxDisplayObj *pObj);

Int32 chains_vipSingleCamFrmcpyEve_SgxDisplay_Stop(chains_vipSingleCamFrmcpyEve_SgxDisplayObj *pObj);

Int32 chains_vipSingleCamFrmcpyEve_SgxDisplay_Delete(chains_vipSingleCamFrmcpyEve_SgxDisplayObj *pObj);

Void chains_vipSingleCamFrmcpyEve_SgxDisplay_printBufferStatistics(chains_vipSingleCamFrmcpyEve_SgxDisplayObj *pObj);

Void chains_vipSingleCamFrmcpyEve_SgxDisplay_printStatistics(chains_vipSingleCamFrmcpyEve_SgxDisplayObj *pObj);

Void chains_vipSingleCamFrmcpyEve_SgxDisplay_SetAppPrms(chains_vipSingleCamFrmcpyEve_SgxDisplayObj *pObj, Void *appObj);

#endif /* _chains_vipSingleCamFrmcpyEve_SgxDisplay_H_ */
