/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/

#ifndef _chains_vipSingleCameraSfm_H_
#define _chains_vipSingleCameraSfm_H_

#include <include/link_api/system.h>
#include <include/link_api/captureLink.h>
#include <include/link_api/dupLink.h>
#include <include/link_api/algorithmLink_sparseOpticalFlow.h>
#include <include/link_api/algorithmLink_sfm.h>
#include <include/link_api/mergeLink.h>
#include <include/link_api/syncLink.h>
#include <include/link_api/algorithmLink_objectDraw.h>
#include <include/link_api/ipcLink.h>
#include <include/link_api/grpxSrcLink.h>
#include <include/link_api/displayLink.h>

typedef struct {
       UInt32    CaptureLinkID;
       UInt32    Dup_captureLinkID;
       UInt32    IPCOut_IPU1_0_EVE1_1LinkID;
       UInt32    IPCIn_EVE1_IPU1_0_0LinkID;
       UInt32    Alg_SparseOpticalFlowLinkID;
       UInt32    IPCOut_EVE1_DSP1_0LinkID;
       UInt32    IPCIn_DSP1_EVE1_1LinkID;
       UInt32    Alg_SfmLinkID;
       UInt32    IPCOut_IPU1_0_DSP1_0LinkID;
       UInt32    IPCIn_DSP1_IPU1_0_0LinkID;
       UInt32    Merge_algLinkID;
       UInt32    Sync_algLinkID;
       UInt32    Alg_ObjectDrawLinkID;
       UInt32    IPCOut_DSP1_IPU1_0_0LinkID;
       UInt32    IPCIn_IPU1_0_DSP1_0LinkID;
       UInt32    Display_algLinkID;
       UInt32    GrpxSrcLinkID;
       UInt32    Display_GrpxLinkID;

       CaptureLink_CreateParams                CapturePrm;
       DupLink_CreateParams                    Dup_capturePrm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_EVE1_1Prm;
       IpcLink_CreateParams                    IPCIn_EVE1_IPU1_0_0Prm;
       AlgorithmLink_SparseOpticalFlowCreateParams Alg_SparseOpticalFlowPrm;
       IpcLink_CreateParams                    IPCOut_EVE1_DSP1_0Prm;
       IpcLink_CreateParams                    IPCIn_DSP1_EVE1_1Prm;
       AlgorithmLink_SfmCreateParams           Alg_SfmPrm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_DSP1_0Prm;
       IpcLink_CreateParams                    IPCIn_DSP1_IPU1_0_0Prm;
       MergeLink_CreateParams                  Merge_algPrm;
       SyncLink_CreateParams                   Sync_algPrm;
       AlgorithmLink_ObjectDrawCreateParams    Alg_ObjectDrawPrm;
       IpcLink_CreateParams                    IPCOut_DSP1_IPU1_0_0Prm;
       IpcLink_CreateParams                    IPCIn_IPU1_0_DSP1_0Prm;
       DisplayLink_CreateParams                Display_algPrm;
       GrpxSrcLink_CreateParams                GrpxSrcPrm;
       DisplayLink_CreateParams                Display_GrpxPrm;
} chains_vipSingleCameraSfmObj;

Void chains_vipSingleCameraSfm_SetLinkId(chains_vipSingleCameraSfmObj *pObj);

Void chains_vipSingleCameraSfm_ResetLinkPrms(chains_vipSingleCameraSfmObj *pObj);

Void chains_vipSingleCameraSfm_SetPrms(chains_vipSingleCameraSfmObj *pObj);

Void chains_vipSingleCameraSfm_ConnectLinks(chains_vipSingleCameraSfmObj *pObj);

Int32 chains_vipSingleCameraSfm_Create(chains_vipSingleCameraSfmObj *pObj, Void *appObj);

Int32 chains_vipSingleCameraSfm_Start(chains_vipSingleCameraSfmObj *pObj);

Int32 chains_vipSingleCameraSfm_Stop(chains_vipSingleCameraSfmObj *pObj);

Int32 chains_vipSingleCameraSfm_Delete(chains_vipSingleCameraSfmObj *pObj);

Void chains_vipSingleCameraSfm_printBufferStatistics(chains_vipSingleCameraSfmObj *pObj);

Void chains_vipSingleCameraSfm_printStatistics(chains_vipSingleCameraSfmObj *pObj);

Void chains_vipSingleCameraSfm_SetAppPrms(chains_vipSingleCameraSfmObj *pObj, Void *appObj);

#endif /* _chains_vipSingleCameraSfm_H_ */
