/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/

#ifndef _chains_issMultCaptIspDeWarp3dSv_H_
#define _chains_issMultCaptIspDeWarp3dSv_H_

#include <include/link_api/system.h>
#include <include/link_api/issCaptureLink.h>
#include <include/link_api/issM2mIspLink.h>
#include <include/link_api/algorithmLink_issAewb.h>
#include <include/link_api/syncLink.h>
#include <include/link_api/algorithmLink_deWarp.h>
#include <include/link_api/algorithmLink_synthesis.h>
#include <include/link_api/ipcLink.h>
#include <include/link_api/displayLink.h>
#include <include/link_api/algorithmLink_photoAlignment.h>

typedef struct {
       UInt32    IssCaptureLinkID;
       UInt32    IssM2mIspLinkID;
       UInt32    Alg_IssAewbLinkID;
       UInt32    Sync_dewarpLinkID;
       UInt32    Alg_DeWarpLinkID;
       UInt32    IPCOut_IPU1_0_DSP1_0LinkID;
       UInt32    IPCIn_DSP1_IPU1_0_0LinkID;
       UInt32    Alg_SynthesisLinkID;
       UInt32    IPCOut_DSP1_IPU1_0_0LinkID;
       UInt32    IPCIn_IPU1_0_DSP1_0LinkID;
       UInt32    Display_VideoLinkID;
       UInt32    Alg_PhotoAlignLinkID;

       IssCaptureLink_CreateParams             IssCapturePrm;
       IssM2mIspLink_CreateParams              IssM2mIspPrm;
       AlgorithmLink_IssAewbCreateParams       Alg_IssAewbPrm;
       SyncLink_CreateParams                   Sync_dewarpPrm;
       AlgLink_DeWarpCreateParams              Alg_DeWarpPrm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_DSP1_0Prm;
       IpcLink_CreateParams                    IPCIn_DSP1_IPU1_0_0Prm;
       AlgorithmLink_SynthesisCreateParams     Alg_SynthesisPrm;
       IpcLink_CreateParams                    IPCOut_DSP1_IPU1_0_0Prm;
       IpcLink_CreateParams                    IPCIn_IPU1_0_DSP1_0Prm;
       DisplayLink_CreateParams                Display_VideoPrm;
       AlgorithmLink_PAlignCreateParams        Alg_PhotoAlignPrm;
} chains_issMultCaptIspDeWarp3dSvObj;

Void chains_issMultCaptIspDeWarp3dSv_SetLinkId(chains_issMultCaptIspDeWarp3dSvObj *pObj);

Void chains_issMultCaptIspDeWarp3dSv_ResetLinkPrms(chains_issMultCaptIspDeWarp3dSvObj *pObj);

Void chains_issMultCaptIspDeWarp3dSv_SetPrms(chains_issMultCaptIspDeWarp3dSvObj *pObj);

Void chains_issMultCaptIspDeWarp3dSv_ConnectLinks(chains_issMultCaptIspDeWarp3dSvObj *pObj);

Int32 chains_issMultCaptIspDeWarp3dSv_Create(chains_issMultCaptIspDeWarp3dSvObj *pObj, Void *appObj);

Int32 chains_issMultCaptIspDeWarp3dSv_Start(chains_issMultCaptIspDeWarp3dSvObj *pObj);

Int32 chains_issMultCaptIspDeWarp3dSv_Stop(chains_issMultCaptIspDeWarp3dSvObj *pObj);

Int32 chains_issMultCaptIspDeWarp3dSv_Delete(chains_issMultCaptIspDeWarp3dSvObj *pObj);

Void chains_issMultCaptIspDeWarp3dSv_printBufferStatistics(chains_issMultCaptIspDeWarp3dSvObj *pObj);

Void chains_issMultCaptIspDeWarp3dSv_printStatistics(chains_issMultCaptIspDeWarp3dSvObj *pObj);

Void chains_issMultCaptIspDeWarp3dSv_SetAppPrms(chains_issMultCaptIspDeWarp3dSvObj *pObj, Void *appObj);

#endif /* _chains_issMultCaptIspDeWarp3dSv_H_ */
