/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/

#ifndef _chains_issMultCaptIspDeWarp3dSv_grpx_H_
#define _chains_issMultCaptIspDeWarp3dSv_grpx_H_

#include <include/link_api/system.h>
#include <include/link_api/grpxSrcLink.h>
#include <include/link_api/displayLink.h>

typedef struct {
       UInt32    GrpxSrcLinkID;
       UInt32    Display_GrpxLinkID;

       GrpxSrcLink_CreateParams                GrpxSrcPrm;
       DisplayLink_CreateParams                Display_GrpxPrm;
} chains_issMultCaptIspDeWarp3dSv_grpxObj;

Void chains_issMultCaptIspDeWarp3dSv_grpx_SetLinkId(chains_issMultCaptIspDeWarp3dSv_grpxObj *pObj);

Void chains_issMultCaptIspDeWarp3dSv_grpx_ResetLinkPrms(chains_issMultCaptIspDeWarp3dSv_grpxObj *pObj);

Void chains_issMultCaptIspDeWarp3dSv_grpx_SetPrms(chains_issMultCaptIspDeWarp3dSv_grpxObj *pObj);

Void chains_issMultCaptIspDeWarp3dSv_grpx_ConnectLinks(chains_issMultCaptIspDeWarp3dSv_grpxObj *pObj);

Int32 chains_issMultCaptIspDeWarp3dSv_grpx_Create(chains_issMultCaptIspDeWarp3dSv_grpxObj *pObj, Void *appObj);

Int32 chains_issMultCaptIspDeWarp3dSv_grpx_Start(chains_issMultCaptIspDeWarp3dSv_grpxObj *pObj);

Int32 chains_issMultCaptIspDeWarp3dSv_grpx_Stop(chains_issMultCaptIspDeWarp3dSv_grpxObj *pObj);

Int32 chains_issMultCaptIspDeWarp3dSv_grpx_Delete(chains_issMultCaptIspDeWarp3dSv_grpxObj *pObj);

Void chains_issMultCaptIspDeWarp3dSv_grpx_printBufferStatistics(chains_issMultCaptIspDeWarp3dSv_grpxObj *pObj);

Void chains_issMultCaptIspDeWarp3dSv_grpx_printStatistics(chains_issMultCaptIspDeWarp3dSv_grpxObj *pObj);

Void chains_issMultCaptIspDeWarp3dSv_grpx_SetAppPrms(chains_issMultCaptIspDeWarp3dSv_grpxObj *pObj, Void *appObj);

#endif /* _chains_issMultCaptIspDeWarp3dSv_grpx_H_ */
