/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/

#ifndef _chains_vipSingleCamOpenCVCannySgxDisplay_H_
#define _chains_vipSingleCamOpenCVCannySgxDisplay_H_

#include <include/link_api/system.h>
#include <include/link_api/captureLink.h>
#include <include/link_api/algorithmLink_opencvcanny.h>
#include <include/link_api/sgxFrmcpyLink.h>
#include <include/link_api/ipcLink.h>
#include <include/link_api/grpxSrcLink.h>
#include <include/link_api/displayLink.h>

typedef struct {
       UInt32    CaptureLinkID;
       UInt32    IPCOut_IPU1_0_A15_0_0LinkID;
       UInt32    IPCIn_A15_0_IPU1_0_0LinkID;
       UInt32    Alg_OpenCVCannyLinkID;
       UInt32    SgxFrmcpyLinkID;
       UInt32    IPCOut_A15_0_IPU1_0_0LinkID;
       UInt32    IPCIn_IPU1_0_A15_0_0LinkID;
       UInt32    Display_M4LinkID;
       UInt32    GrpxSrcLinkID;
       UInt32    Display_GrpxLinkID;

       CaptureLink_CreateParams                CapturePrm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_A15_0_0Prm;
       IpcLink_CreateParams                    IPCIn_A15_0_IPU1_0_0Prm;
       Alg_OpenCVCanny_CreateParams            Alg_OpenCVCannyPrm;
       SgxFrmcpyLink_CreateParams              SgxFrmcpyPrm;
       IpcLink_CreateParams                    IPCOut_A15_0_IPU1_0_0Prm;
       IpcLink_CreateParams                    IPCIn_IPU1_0_A15_0_0Prm;
       DisplayLink_CreateParams                Display_M4Prm;
       GrpxSrcLink_CreateParams                GrpxSrcPrm;
       DisplayLink_CreateParams                Display_GrpxPrm;
} chains_vipSingleCamOpenCVCannySgxDisplayObj;

Void chains_vipSingleCamOpenCVCannySgxDisplay_SetLinkId(chains_vipSingleCamOpenCVCannySgxDisplayObj *pObj);

Void chains_vipSingleCamOpenCVCannySgxDisplay_ResetLinkPrms(chains_vipSingleCamOpenCVCannySgxDisplayObj *pObj);

Void chains_vipSingleCamOpenCVCannySgxDisplay_SetPrms(chains_vipSingleCamOpenCVCannySgxDisplayObj *pObj);

Void chains_vipSingleCamOpenCVCannySgxDisplay_ConnectLinks(chains_vipSingleCamOpenCVCannySgxDisplayObj *pObj);

Int32 chains_vipSingleCamOpenCVCannySgxDisplay_Create(chains_vipSingleCamOpenCVCannySgxDisplayObj *pObj, Void *appObj);

Int32 chains_vipSingleCamOpenCVCannySgxDisplay_Start(chains_vipSingleCamOpenCVCannySgxDisplayObj *pObj);

Int32 chains_vipSingleCamOpenCVCannySgxDisplay_Stop(chains_vipSingleCamOpenCVCannySgxDisplayObj *pObj);

Int32 chains_vipSingleCamOpenCVCannySgxDisplay_Delete(chains_vipSingleCamOpenCVCannySgxDisplayObj *pObj);

Void chains_vipSingleCamOpenCVCannySgxDisplay_printBufferStatistics(chains_vipSingleCamOpenCVCannySgxDisplayObj *pObj);

Void chains_vipSingleCamOpenCVCannySgxDisplay_printStatistics(chains_vipSingleCamOpenCVCannySgxDisplayObj *pObj);

Void chains_vipSingleCamOpenCVCannySgxDisplay_SetAppPrms(chains_vipSingleCamOpenCVCannySgxDisplayObj *pObj, Void *appObj);

#endif /* _chains_vipSingleCamOpenCVCannySgxDisplay_H_ */
