/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/

#ifndef _chains_issMultCaptIsp2d3dSv_H_
#define _chains_issMultCaptIsp2d3dSv_H_

#include <include/link_api/system.h>
#include <include/link_api/issCaptureLink.h>
#include <include/link_api/issM2mIspLink.h>
#include <include/link_api/algorithmLink_issAewb.h>
#include <include/link_api/syncLink.h>
#include <include/link_api/dupLink.h>
#include <include/link_api/algorithmLink_geometricAlignment.h>
#include <include/link_api/algorithmLink_deWarp.h>
#include <include/link_api/algorithmLink_synthesis.h>
#include <include/link_api/ipcLink.h>
#include <include/link_api/algorithmLink_photoAlignment.h>
#include <include/link_api/grpxSrcLink.h>
#include <include/link_api/displayLink.h>

typedef struct {
       UInt32    IssCaptureLinkID;
       UInt32    IssM2mIspLinkID;
       UInt32    Alg_IssAewbLinkID;
       UInt32    SyncLinkID;
       UInt32    Dup_svLinkID;
       UInt32    Dup_2dLinkID;
       UInt32    IPCOut_IPU1_0_DSP2_2LinkID;
       UInt32    IPCIn_DSP2_IPU1_0_1LinkID;
       UInt32    IPCOut_IPU1_0_DSP2_1LinkID;
       UInt32    IPCIn_DSP2_IPU1_0_0LinkID;
       UInt32    Alg_GeoAlign_2dLinkID;
       UInt32    Alg_Synthesis_2dLinkID;
       UInt32    IPCOut_DSP2_IPU1_0_0LinkID;
       UInt32    IPCIn_IPU1_0_DSP2_1LinkID;
       UInt32    Display_2dLinkID;
       UInt32    Alg_PhotoAlign_2dLinkID;
       UInt32    Alg_DeWarpLinkID;
       UInt32    IPCOut_IPU1_0_DSP1_0LinkID;
       UInt32    IPCIn_DSP1_IPU1_0_0LinkID;
       UInt32    Alg_Synthesis_3dLinkID;
       UInt32    IPCOut_DSP1_IPU1_0_0LinkID;
       UInt32    IPCIn_IPU1_0_DSP1_0LinkID;
       UInt32    Display_3dLinkID;
       UInt32    Alg_PhotoAlign_3dLinkID;
       UInt32    GrpxSrcLinkID;
       UInt32    Display_GrpxLinkID;

       IssCaptureLink_CreateParams             IssCapturePrm;
       IssM2mIspLink_CreateParams              IssM2mIspPrm;
       AlgorithmLink_IssAewbCreateParams       Alg_IssAewbPrm;
       SyncLink_CreateParams                   SyncPrm;
       DupLink_CreateParams                    Dup_svPrm;
       DupLink_CreateParams                    Dup_2dPrm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_DSP2_2Prm;
       IpcLink_CreateParams                    IPCIn_DSP2_IPU1_0_1Prm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_DSP2_1Prm;
       IpcLink_CreateParams                    IPCIn_DSP2_IPU1_0_0Prm;
       AlgorithmLink_GAlignCreateParams        Alg_GeoAlign_2dPrm;
       AlgorithmLink_SynthesisCreateParams     Alg_Synthesis_2dPrm;
       IpcLink_CreateParams                    IPCOut_DSP2_IPU1_0_0Prm;
       IpcLink_CreateParams                    IPCIn_IPU1_0_DSP2_1Prm;
       DisplayLink_CreateParams                Display_2dPrm;
       AlgorithmLink_PAlignCreateParams        Alg_PhotoAlign_2dPrm;
       AlgLink_DeWarpCreateParams              Alg_DeWarpPrm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_DSP1_0Prm;
       IpcLink_CreateParams                    IPCIn_DSP1_IPU1_0_0Prm;
       AlgorithmLink_SynthesisCreateParams     Alg_Synthesis_3dPrm;
       IpcLink_CreateParams                    IPCOut_DSP1_IPU1_0_0Prm;
       IpcLink_CreateParams                    IPCIn_IPU1_0_DSP1_0Prm;
       DisplayLink_CreateParams                Display_3dPrm;
       AlgorithmLink_PAlignCreateParams        Alg_PhotoAlign_3dPrm;
       GrpxSrcLink_CreateParams                GrpxSrcPrm;
       DisplayLink_CreateParams                Display_GrpxPrm;
} chains_issMultCaptIsp2d3dSvObj;

Void chains_issMultCaptIsp2d3dSv_SetLinkId(chains_issMultCaptIsp2d3dSvObj *pObj);

Void chains_issMultCaptIsp2d3dSv_ResetLinkPrms(chains_issMultCaptIsp2d3dSvObj *pObj);

Void chains_issMultCaptIsp2d3dSv_SetPrms(chains_issMultCaptIsp2d3dSvObj *pObj);

Void chains_issMultCaptIsp2d3dSv_ConnectLinks(chains_issMultCaptIsp2d3dSvObj *pObj);

Int32 chains_issMultCaptIsp2d3dSv_Create(chains_issMultCaptIsp2d3dSvObj *pObj, Void *appObj);

Int32 chains_issMultCaptIsp2d3dSv_Start(chains_issMultCaptIsp2d3dSvObj *pObj);

Int32 chains_issMultCaptIsp2d3dSv_Stop(chains_issMultCaptIsp2d3dSvObj *pObj);

Int32 chains_issMultCaptIsp2d3dSv_Delete(chains_issMultCaptIsp2d3dSvObj *pObj);

Void chains_issMultCaptIsp2d3dSv_printBufferStatistics(chains_issMultCaptIsp2d3dSvObj *pObj);

Void chains_issMultCaptIsp2d3dSv_printStatistics(chains_issMultCaptIsp2d3dSvObj *pObj);

Void chains_issMultCaptIsp2d3dSv_SetAppPrms(chains_issMultCaptIsp2d3dSvObj *pObj, Void *appObj);

#endif /* _chains_issMultCaptIsp2d3dSv_H_ */
