/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/

#ifndef _chains_vipSingleCameraSafeFrameCopy_H_
#define _chains_vipSingleCameraSafeFrameCopy_H_

#include <include/link_api/system.h>
#include <include/link_api/captureLink.h>
#include <include/link_api/algorithmLink_safeFrameCopy.h>
#include <include/link_api/ipcLink.h>
#include <include/link_api/grpxSrcLink.h>
#include <include/link_api/displayLink.h>

typedef struct {
       UInt32    CaptureLinkID;
       UInt32    IPCOut_IPU1_0_A15_0_0LinkID;
       UInt32    IPCIn_A15_0_IPU1_0_0LinkID;
       UInt32    Alg_SafeFrameCopyLinkID;
       UInt32    IPCOut_A15_0_IPU1_0_0LinkID;
       UInt32    IPCIn_IPU1_0_A15_0_0LinkID;
       UInt32    Display_VideoLinkID;
       UInt32    GrpxSrcLinkID;
       UInt32    Display_GrpxLinkID;

       CaptureLink_CreateParams                CapturePrm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_A15_0_0Prm;
       IpcLink_CreateParams                    IPCIn_A15_0_IPU1_0_0Prm;
       AlgorithmLink_SafeFrameCopyCreateParams Alg_SafeFrameCopyPrm;
       IpcLink_CreateParams                    IPCOut_A15_0_IPU1_0_0Prm;
       IpcLink_CreateParams                    IPCIn_IPU1_0_A15_0_0Prm;
       DisplayLink_CreateParams                Display_VideoPrm;
       GrpxSrcLink_CreateParams                GrpxSrcPrm;
       DisplayLink_CreateParams                Display_GrpxPrm;
} chains_vipSingleCameraSafeFrameCopyObj;

Void chains_vipSingleCameraSafeFrameCopy_SetLinkId(chains_vipSingleCameraSafeFrameCopyObj *pObj);

Void chains_vipSingleCameraSafeFrameCopy_ResetLinkPrms(chains_vipSingleCameraSafeFrameCopyObj *pObj);

Void chains_vipSingleCameraSafeFrameCopy_SetPrms(chains_vipSingleCameraSafeFrameCopyObj *pObj);

Void chains_vipSingleCameraSafeFrameCopy_ConnectLinks(chains_vipSingleCameraSafeFrameCopyObj *pObj);

Int32 chains_vipSingleCameraSafeFrameCopy_Create(chains_vipSingleCameraSafeFrameCopyObj *pObj, Void *appObj);

Int32 chains_vipSingleCameraSafeFrameCopy_Start(chains_vipSingleCameraSafeFrameCopyObj *pObj);

Int32 chains_vipSingleCameraSafeFrameCopy_Stop(chains_vipSingleCameraSafeFrameCopyObj *pObj);

Int32 chains_vipSingleCameraSafeFrameCopy_Delete(chains_vipSingleCameraSafeFrameCopyObj *pObj);

Void chains_vipSingleCameraSafeFrameCopy_printBufferStatistics(chains_vipSingleCameraSafeFrameCopyObj *pObj);

Void chains_vipSingleCameraSafeFrameCopy_printStatistics(chains_vipSingleCameraSafeFrameCopyObj *pObj);

Void chains_vipSingleCameraSafeFrameCopy_SetAppPrms(chains_vipSingleCameraSafeFrameCopyObj *pObj, Void *appObj);

#endif /* _chains_vipSingleCameraSafeFrameCopy_H_ */
