/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/

#ifndef _chains_vipSingleCamConnectorLinksA15SgxDisplay_H_
#define _chains_vipSingleCamConnectorLinksA15SgxDisplay_H_

#include <include/link_api/system.h>
#include <include/link_api/captureLink.h>
#include <include/link_api/dupLink.h>
#include <include/link_api/algorithmLink_frameCopy.h>
#include <include/link_api/mergeLink.h>
#include <include/link_api/selectLink.h>
#include <include/link_api/gateLink.h>
#include <include/link_api/nullLink.h>
#include <include/link_api/sgxFrmcpyLink.h>
#include <include/link_api/ipcLink.h>
#include <include/link_api/grpxSrcLink.h>
#include <include/link_api/displayLink.h>

typedef struct {
       UInt32    CaptureLinkID;
       UInt32    IPCOut_IPU1_0_A15_0_0LinkID;
       UInt32    IPCIn_A15_0_IPU1_0_0LinkID;
       UInt32    Dup_1LinkID;
       UInt32    Alg_FrameCopy_2LinkID;
       UInt32    Alg_FrameCopy_1LinkID;
       UInt32    MergeLinkID;
       UInt32    Select_1LinkID;
       UInt32    Gate_1LinkID;
       UInt32    NullLinkID;
       UInt32    SgxFrmcpyLinkID;
       UInt32    IPCOut_A15_0_IPU1_0_0LinkID;
       UInt32    IPCIn_IPU1_0_A15_0_0LinkID;
       UInt32    Display_M4LinkID;
       UInt32    GrpxSrcLinkID;
       UInt32    Display_GrpxLinkID;

       CaptureLink_CreateParams                CapturePrm;
       IpcLink_CreateParams                    IPCOut_IPU1_0_A15_0_0Prm;
       IpcLink_CreateParams                    IPCIn_A15_0_IPU1_0_0Prm;
       DupLink_CreateParams                    Dup_1Prm;
       AlgorithmLink_FrameCopyCreateParams     Alg_FrameCopy_2Prm;
       AlgorithmLink_FrameCopyCreateParams     Alg_FrameCopy_1Prm;
       MergeLink_CreateParams                  MergePrm;
       SelectLink_CreateParams                 Select_1Prm;
       GateLink_CreateParams                   Gate_1Prm;
       NullLink_CreateParams                   NullPrm;
       SgxFrmcpyLink_CreateParams              SgxFrmcpyPrm;
       IpcLink_CreateParams                    IPCOut_A15_0_IPU1_0_0Prm;
       IpcLink_CreateParams                    IPCIn_IPU1_0_A15_0_0Prm;
       DisplayLink_CreateParams                Display_M4Prm;
       GrpxSrcLink_CreateParams                GrpxSrcPrm;
       DisplayLink_CreateParams                Display_GrpxPrm;
} chains_vipSingleCamConnectorLinksA15SgxDisplayObj;

Void chains_vipSingleCamConnectorLinksA15SgxDisplay_SetLinkId(chains_vipSingleCamConnectorLinksA15SgxDisplayObj *pObj);

Void chains_vipSingleCamConnectorLinksA15SgxDisplay_ResetLinkPrms(chains_vipSingleCamConnectorLinksA15SgxDisplayObj *pObj);

Void chains_vipSingleCamConnectorLinksA15SgxDisplay_SetPrms(chains_vipSingleCamConnectorLinksA15SgxDisplayObj *pObj);

Void chains_vipSingleCamConnectorLinksA15SgxDisplay_ConnectLinks(chains_vipSingleCamConnectorLinksA15SgxDisplayObj *pObj);

Int32 chains_vipSingleCamConnectorLinksA15SgxDisplay_Create(chains_vipSingleCamConnectorLinksA15SgxDisplayObj *pObj, Void *appObj);

Int32 chains_vipSingleCamConnectorLinksA15SgxDisplay_Start(chains_vipSingleCamConnectorLinksA15SgxDisplayObj *pObj);

Int32 chains_vipSingleCamConnectorLinksA15SgxDisplay_Stop(chains_vipSingleCamConnectorLinksA15SgxDisplayObj *pObj);

Int32 chains_vipSingleCamConnectorLinksA15SgxDisplay_Delete(chains_vipSingleCamConnectorLinksA15SgxDisplayObj *pObj);

Void chains_vipSingleCamConnectorLinksA15SgxDisplay_printBufferStatistics(chains_vipSingleCamConnectorLinksA15SgxDisplayObj *pObj);

Void chains_vipSingleCamConnectorLinksA15SgxDisplay_printStatistics(chains_vipSingleCamConnectorLinksA15SgxDisplayObj *pObj);

Void chains_vipSingleCamConnectorLinksA15SgxDisplay_SetAppPrms(chains_vipSingleCamConnectorLinksA15SgxDisplayObj *pObj, Void *appObj);

#endif /* _chains_vipSingleCamConnectorLinksA15SgxDisplay_H_ */
